// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_top_prepare_input_buf_func_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_s_dout,
        input_s_empty_n,
        input_s_read,
        input_s_num_data_valid,
        input_s_fifo_cap,
        input_buf_0_0_address0,
        input_buf_0_0_ce0,
        input_buf_0_0_we0,
        input_buf_0_0_d0,
        input_buf_0_1_address0,
        input_buf_0_1_ce0,
        input_buf_0_1_we0,
        input_buf_0_1_d0,
        input_buf_0_2_address0,
        input_buf_0_2_ce0,
        input_buf_0_2_we0,
        input_buf_0_2_d0,
        input_buf_1_0_address0,
        input_buf_1_0_ce0,
        input_buf_1_0_we0,
        input_buf_1_0_d0,
        input_buf_1_1_address0,
        input_buf_1_1_ce0,
        input_buf_1_1_we0,
        input_buf_1_1_d0,
        input_buf_1_2_address0,
        input_buf_1_2_ce0,
        input_buf_1_2_we0,
        input_buf_1_2_d0,
        input_buf_2_0_address0,
        input_buf_2_0_ce0,
        input_buf_2_0_we0,
        input_buf_2_0_d0,
        input_buf_2_1_address0,
        input_buf_2_1_ce0,
        input_buf_2_1_we0,
        input_buf_2_1_d0,
        input_buf_2_2_address0,
        input_buf_2_2_ce0,
        input_buf_2_2_we0,
        input_buf_2_2_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] input_s_dout;
input   input_s_empty_n;
output   input_s_read;
input  [8:0] input_s_num_data_valid;
input  [8:0] input_s_fifo_cap;
output  [5:0] input_buf_0_0_address0;
output   input_buf_0_0_ce0;
output   input_buf_0_0_we0;
output  [15:0] input_buf_0_0_d0;
output  [5:0] input_buf_0_1_address0;
output   input_buf_0_1_ce0;
output   input_buf_0_1_we0;
output  [15:0] input_buf_0_1_d0;
output  [5:0] input_buf_0_2_address0;
output   input_buf_0_2_ce0;
output   input_buf_0_2_we0;
output  [15:0] input_buf_0_2_d0;
output  [5:0] input_buf_1_0_address0;
output   input_buf_1_0_ce0;
output   input_buf_1_0_we0;
output  [15:0] input_buf_1_0_d0;
output  [5:0] input_buf_1_1_address0;
output   input_buf_1_1_ce0;
output   input_buf_1_1_we0;
output  [15:0] input_buf_1_1_d0;
output  [5:0] input_buf_1_2_address0;
output   input_buf_1_2_ce0;
output   input_buf_1_2_we0;
output  [15:0] input_buf_1_2_d0;
output  [5:0] input_buf_2_0_address0;
output   input_buf_2_0_ce0;
output   input_buf_2_0_we0;
output  [15:0] input_buf_2_0_d0;
output  [5:0] input_buf_2_1_address0;
output   input_buf_2_1_ce0;
output   input_buf_2_1_we0;
output  [15:0] input_buf_2_1_d0;
output  [5:0] input_buf_2_2_address0;
output   input_buf_2_2_ce0;
output   input_buf_2_2_we0;
output  [15:0] input_buf_2_2_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] input_buf_0_0_address0;
reg input_buf_0_0_ce0;
reg input_buf_0_0_we0;
reg[15:0] input_buf_0_0_d0;
reg[5:0] input_buf_0_1_address0;
reg input_buf_0_1_ce0;
reg input_buf_0_1_we0;
reg[15:0] input_buf_0_1_d0;
reg[5:0] input_buf_0_2_address0;
reg input_buf_0_2_ce0;
reg input_buf_0_2_we0;
reg[15:0] input_buf_0_2_d0;
reg[5:0] input_buf_1_0_address0;
reg input_buf_1_0_ce0;
reg input_buf_1_0_we0;
reg[15:0] input_buf_1_0_d0;
reg[5:0] input_buf_1_1_address0;
reg input_buf_1_1_ce0;
reg input_buf_1_1_we0;
reg[15:0] input_buf_1_1_d0;
reg[5:0] input_buf_1_2_address0;
reg input_buf_1_2_ce0;
reg input_buf_1_2_we0;
reg[15:0] input_buf_1_2_d0;
reg[5:0] input_buf_2_0_address0;
reg input_buf_2_0_ce0;
reg input_buf_2_0_we0;
reg[15:0] input_buf_2_0_d0;
reg[5:0] input_buf_2_1_address0;
reg input_buf_2_1_ce0;
reg input_buf_2_1_we0;
reg[15:0] input_buf_2_1_d0;
reg[5:0] input_buf_2_2_address0;
reg input_buf_2_2_ce0;
reg input_buf_2_2_we0;
reg[15:0] input_buf_2_2_d0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_idle;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_ready;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_idle;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_ready;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_s_read;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0;
wire    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0;
reg    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg = 1'b0;
#0 grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg = 1'b0;
end

cnn_top_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3 grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start),
    .ap_done(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done),
    .ap_idle(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_idle),
    .ap_ready(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_ready),
    .input_buf_2_2_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0),
    .input_buf_2_2_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0),
    .input_buf_2_2_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0),
    .input_buf_2_2_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0),
    .input_buf_2_1_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0),
    .input_buf_2_1_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0),
    .input_buf_2_1_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0),
    .input_buf_2_1_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0),
    .input_buf_2_0_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0),
    .input_buf_2_0_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0),
    .input_buf_2_0_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0),
    .input_buf_2_0_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0),
    .input_buf_1_2_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0),
    .input_buf_1_2_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0),
    .input_buf_1_2_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0),
    .input_buf_1_2_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0),
    .input_buf_1_1_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0),
    .input_buf_1_1_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0),
    .input_buf_1_1_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0),
    .input_buf_1_1_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0),
    .input_buf_1_0_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0),
    .input_buf_1_0_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0),
    .input_buf_1_0_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0),
    .input_buf_1_0_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0),
    .input_buf_0_2_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0),
    .input_buf_0_2_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0),
    .input_buf_0_2_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0),
    .input_buf_0_2_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0),
    .input_buf_0_1_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0),
    .input_buf_0_1_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0),
    .input_buf_0_1_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0),
    .input_buf_0_1_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0),
    .input_buf_0_0_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0),
    .input_buf_0_0_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0),
    .input_buf_0_0_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0),
    .input_buf_0_0_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0)
);

cnn_top_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5 grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start),
    .ap_done(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done),
    .ap_idle(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_idle),
    .ap_ready(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_ready),
    .input_s_dout(input_s_dout),
    .input_s_empty_n(input_s_empty_n),
    .input_s_read(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_s_read),
    .input_s_num_data_valid(9'd0),
    .input_s_fifo_cap(9'd0),
    .input_buf_2_2_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0),
    .input_buf_2_2_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0),
    .input_buf_2_2_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0),
    .input_buf_2_2_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0),
    .input_buf_2_1_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0),
    .input_buf_2_1_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0),
    .input_buf_2_1_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0),
    .input_buf_2_1_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0),
    .input_buf_2_0_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0),
    .input_buf_2_0_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0),
    .input_buf_2_0_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0),
    .input_buf_2_0_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0),
    .input_buf_1_2_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0),
    .input_buf_1_2_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0),
    .input_buf_1_2_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0),
    .input_buf_1_2_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0),
    .input_buf_1_1_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0),
    .input_buf_1_1_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0),
    .input_buf_1_1_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0),
    .input_buf_1_1_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0),
    .input_buf_1_0_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0),
    .input_buf_1_0_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0),
    .input_buf_1_0_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0),
    .input_buf_1_0_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0),
    .input_buf_0_2_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0),
    .input_buf_0_2_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0),
    .input_buf_0_2_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0),
    .input_buf_0_2_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0),
    .input_buf_0_1_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0),
    .input_buf_0_1_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0),
    .input_buf_0_1_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0),
    .input_buf_0_1_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0),
    .input_buf_0_0_address0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0),
    .input_buf_0_0_ce0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0),
    .input_buf_0_0_we0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0),
    .input_buf_0_0_d0(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_ready == 1'b1)) begin
            grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_ready == 1'b1)) begin
            grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & (grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done == 1'b1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_0_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_0_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0;
    end else begin
        input_buf_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_0_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_0_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0;
    end else begin
        input_buf_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_0_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_0_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0;
    end else begin
        input_buf_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_0_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_0_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0;
    end else begin
        input_buf_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_1_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_1_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0;
    end else begin
        input_buf_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_1_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_1_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0;
    end else begin
        input_buf_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_1_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_1_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0;
    end else begin
        input_buf_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_1_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_1_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0;
    end else begin
        input_buf_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_2_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_2_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0;
    end else begin
        input_buf_0_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_2_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_2_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0;
    end else begin
        input_buf_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_2_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_2_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0;
    end else begin
        input_buf_0_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_0_2_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_0_2_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0;
    end else begin
        input_buf_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_0_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_0_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0;
    end else begin
        input_buf_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_0_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_0_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0;
    end else begin
        input_buf_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_0_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_0_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0;
    end else begin
        input_buf_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_0_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_0_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0;
    end else begin
        input_buf_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_1_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_1_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0;
    end else begin
        input_buf_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_1_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_1_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0;
    end else begin
        input_buf_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_1_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_1_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0;
    end else begin
        input_buf_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_1_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_1_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0;
    end else begin
        input_buf_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_2_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_2_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0;
    end else begin
        input_buf_1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_2_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_2_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0;
    end else begin
        input_buf_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_2_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_2_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0;
    end else begin
        input_buf_1_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_2_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_2_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0;
    end else begin
        input_buf_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_0_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_0_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0;
    end else begin
        input_buf_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_0_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_0_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0;
    end else begin
        input_buf_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_0_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_0_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0;
    end else begin
        input_buf_2_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_0_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_0_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0;
    end else begin
        input_buf_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_1_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_1_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0;
    end else begin
        input_buf_2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_1_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_1_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0;
    end else begin
        input_buf_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_1_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_1_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0;
    end else begin
        input_buf_2_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_1_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_1_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0;
    end else begin
        input_buf_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_2_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_2_address0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0;
    end else begin
        input_buf_2_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_2_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_2_ce0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0;
    end else begin
        input_buf_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_2_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_2_d0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0;
    end else begin
        input_buf_2_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_2_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_2_we0 = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0;
    end else begin
        input_buf_2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg;

assign grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg;

assign input_s_read = grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_s_read;

endmodule //cnn_top_prepare_input_buf_func_2
