// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_top_load_params_func_Pipeline_VITIS_LOOP_40_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem7_0_AWVALID,
        m_axi_gmem7_0_AWREADY,
        m_axi_gmem7_0_AWADDR,
        m_axi_gmem7_0_AWID,
        m_axi_gmem7_0_AWLEN,
        m_axi_gmem7_0_AWSIZE,
        m_axi_gmem7_0_AWBURST,
        m_axi_gmem7_0_AWLOCK,
        m_axi_gmem7_0_AWCACHE,
        m_axi_gmem7_0_AWPROT,
        m_axi_gmem7_0_AWQOS,
        m_axi_gmem7_0_AWREGION,
        m_axi_gmem7_0_AWUSER,
        m_axi_gmem7_0_WVALID,
        m_axi_gmem7_0_WREADY,
        m_axi_gmem7_0_WDATA,
        m_axi_gmem7_0_WSTRB,
        m_axi_gmem7_0_WLAST,
        m_axi_gmem7_0_WID,
        m_axi_gmem7_0_WUSER,
        m_axi_gmem7_0_ARVALID,
        m_axi_gmem7_0_ARREADY,
        m_axi_gmem7_0_ARADDR,
        m_axi_gmem7_0_ARID,
        m_axi_gmem7_0_ARLEN,
        m_axi_gmem7_0_ARSIZE,
        m_axi_gmem7_0_ARBURST,
        m_axi_gmem7_0_ARLOCK,
        m_axi_gmem7_0_ARCACHE,
        m_axi_gmem7_0_ARPROT,
        m_axi_gmem7_0_ARQOS,
        m_axi_gmem7_0_ARREGION,
        m_axi_gmem7_0_ARUSER,
        m_axi_gmem7_0_RVALID,
        m_axi_gmem7_0_RREADY,
        m_axi_gmem7_0_RDATA,
        m_axi_gmem7_0_RLAST,
        m_axi_gmem7_0_RID,
        m_axi_gmem7_0_RFIFONUM,
        m_axi_gmem7_0_RUSER,
        m_axi_gmem7_0_RRESP,
        m_axi_gmem7_0_BVALID,
        m_axi_gmem7_0_BREADY,
        m_axi_gmem7_0_BRESP,
        m_axi_gmem7_0_BID,
        m_axi_gmem7_0_BUSER,
        sext_ln40,
        local_bias_address0,
        local_bias_ce0,
        local_bias_we0,
        local_bias_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem7_0_AWVALID;
input   m_axi_gmem7_0_AWREADY;
output  [31:0] m_axi_gmem7_0_AWADDR;
output  [0:0] m_axi_gmem7_0_AWID;
output  [31:0] m_axi_gmem7_0_AWLEN;
output  [2:0] m_axi_gmem7_0_AWSIZE;
output  [1:0] m_axi_gmem7_0_AWBURST;
output  [1:0] m_axi_gmem7_0_AWLOCK;
output  [3:0] m_axi_gmem7_0_AWCACHE;
output  [2:0] m_axi_gmem7_0_AWPROT;
output  [3:0] m_axi_gmem7_0_AWQOS;
output  [3:0] m_axi_gmem7_0_AWREGION;
output  [0:0] m_axi_gmem7_0_AWUSER;
output   m_axi_gmem7_0_WVALID;
input   m_axi_gmem7_0_WREADY;
output  [15:0] m_axi_gmem7_0_WDATA;
output  [1:0] m_axi_gmem7_0_WSTRB;
output   m_axi_gmem7_0_WLAST;
output  [0:0] m_axi_gmem7_0_WID;
output  [0:0] m_axi_gmem7_0_WUSER;
output   m_axi_gmem7_0_ARVALID;
input   m_axi_gmem7_0_ARREADY;
output  [31:0] m_axi_gmem7_0_ARADDR;
output  [0:0] m_axi_gmem7_0_ARID;
output  [31:0] m_axi_gmem7_0_ARLEN;
output  [2:0] m_axi_gmem7_0_ARSIZE;
output  [1:0] m_axi_gmem7_0_ARBURST;
output  [1:0] m_axi_gmem7_0_ARLOCK;
output  [3:0] m_axi_gmem7_0_ARCACHE;
output  [2:0] m_axi_gmem7_0_ARPROT;
output  [3:0] m_axi_gmem7_0_ARQOS;
output  [3:0] m_axi_gmem7_0_ARREGION;
output  [0:0] m_axi_gmem7_0_ARUSER;
input   m_axi_gmem7_0_RVALID;
output   m_axi_gmem7_0_RREADY;
input  [15:0] m_axi_gmem7_0_RDATA;
input   m_axi_gmem7_0_RLAST;
input  [0:0] m_axi_gmem7_0_RID;
input  [10:0] m_axi_gmem7_0_RFIFONUM;
input  [0:0] m_axi_gmem7_0_RUSER;
input  [1:0] m_axi_gmem7_0_RRESP;
input   m_axi_gmem7_0_BVALID;
output   m_axi_gmem7_0_BREADY;
input  [1:0] m_axi_gmem7_0_BRESP;
input  [0:0] m_axi_gmem7_0_BID;
input  [0:0] m_axi_gmem7_0_BUSER;
input  [30:0] sext_ln40;
output  [4:0] local_bias_address0;
output   local_bias_ce0;
output   local_bias_we0;
output  [15:0] local_bias_d0;

reg ap_idle;
reg m_axi_gmem7_0_RREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln40_fu_88_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state3;
reg    gmem7_blk_n_R;
wire    ap_CS_fsm_state2;
wire   [4:0] trunc_ln42_fu_106_p1;
reg   [4:0] trunc_ln42_reg_134;
reg   [15:0] gmem7_addr_read_reg_139;
reg    ap_block_state2_pp0_stage1_iter0;
wire   [31:0] zext_ln42_fu_115_p1;
reg   [5:0] oc_fu_48;
wire   [5:0] add_ln40_fu_94_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_oc_1;
reg    local_bias_we0_local;
reg    local_bias_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 oc_fu_48 = 6'd0;
#0 ap_done_reg = 1'b0;
end

cnn_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln40_fu_88_p2 == 1'd0)) begin
            oc_fu_48 <= add_ln40_fu_94_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_48 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem7_addr_read_reg_139 <= m_axi_gmem7_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln42_reg_134 <= trunc_ln42_fu_106_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln40_fu_88_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oc_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_oc_1 = oc_fu_48;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem7_blk_n_R = m_axi_gmem7_0_RVALID;
    end else begin
        gmem7_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        local_bias_ce0_local = 1'b1;
    end else begin
        local_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        local_bias_we0_local = 1'b1;
    end else begin
        local_bias_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem7_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem7_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln40_fu_88_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln40_fu_94_p2 = (ap_sig_allocacmp_oc_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (m_axi_gmem7_0_RVALID == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln40_fu_88_p2 = ((ap_sig_allocacmp_oc_1 == 6'd32) ? 1'b1 : 1'b0);

assign local_bias_address0 = zext_ln42_fu_115_p1;

assign local_bias_ce0 = local_bias_ce0_local;

assign local_bias_d0 = gmem7_addr_read_reg_139;

assign local_bias_we0 = local_bias_we0_local;

assign m_axi_gmem7_0_ARADDR = 32'd0;

assign m_axi_gmem7_0_ARBURST = 2'd0;

assign m_axi_gmem7_0_ARCACHE = 4'd0;

assign m_axi_gmem7_0_ARID = 1'd0;

assign m_axi_gmem7_0_ARLEN = 32'd0;

assign m_axi_gmem7_0_ARLOCK = 2'd0;

assign m_axi_gmem7_0_ARPROT = 3'd0;

assign m_axi_gmem7_0_ARQOS = 4'd0;

assign m_axi_gmem7_0_ARREGION = 4'd0;

assign m_axi_gmem7_0_ARSIZE = 3'd0;

assign m_axi_gmem7_0_ARUSER = 1'd0;

assign m_axi_gmem7_0_ARVALID = 1'b0;

assign m_axi_gmem7_0_AWADDR = 32'd0;

assign m_axi_gmem7_0_AWBURST = 2'd0;

assign m_axi_gmem7_0_AWCACHE = 4'd0;

assign m_axi_gmem7_0_AWID = 1'd0;

assign m_axi_gmem7_0_AWLEN = 32'd0;

assign m_axi_gmem7_0_AWLOCK = 2'd0;

assign m_axi_gmem7_0_AWPROT = 3'd0;

assign m_axi_gmem7_0_AWQOS = 4'd0;

assign m_axi_gmem7_0_AWREGION = 4'd0;

assign m_axi_gmem7_0_AWSIZE = 3'd0;

assign m_axi_gmem7_0_AWUSER = 1'd0;

assign m_axi_gmem7_0_AWVALID = 1'b0;

assign m_axi_gmem7_0_BREADY = 1'b0;

assign m_axi_gmem7_0_WDATA = 16'd0;

assign m_axi_gmem7_0_WID = 1'd0;

assign m_axi_gmem7_0_WLAST = 1'b0;

assign m_axi_gmem7_0_WSTRB = 2'd0;

assign m_axi_gmem7_0_WUSER = 1'd0;

assign m_axi_gmem7_0_WVALID = 1'b0;

assign trunc_ln42_fu_106_p1 = ap_sig_allocacmp_oc_1[4:0];

assign zext_ln42_fu_115_p1 = trunc_ln42_reg_134;

endmodule //cnn_top_load_params_func_Pipeline_VITIS_LOOP_40_5
