// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_top_convolution_func_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_buf_0_0_address0,
        input_buf_0_0_ce0,
        input_buf_0_0_q0,
        input_buf_0_1_address0,
        input_buf_0_1_ce0,
        input_buf_0_1_q0,
        input_buf_0_2_address0,
        input_buf_0_2_ce0,
        input_buf_0_2_q0,
        input_buf_1_0_address0,
        input_buf_1_0_ce0,
        input_buf_1_0_q0,
        input_buf_1_1_address0,
        input_buf_1_1_ce0,
        input_buf_1_1_q0,
        input_buf_1_2_address0,
        input_buf_1_2_ce0,
        input_buf_1_2_q0,
        input_buf_2_0_address0,
        input_buf_2_0_ce0,
        input_buf_2_0_q0,
        input_buf_2_1_address0,
        input_buf_2_1_ce0,
        input_buf_2_1_q0,
        input_buf_2_2_address0,
        input_buf_2_2_ce0,
        input_buf_2_2_q0,
        local_weights_0_0_address0,
        local_weights_0_0_ce0,
        local_weights_0_0_q0,
        local_weights_0_1_address0,
        local_weights_0_1_ce0,
        local_weights_0_1_q0,
        local_weights_0_2_address0,
        local_weights_0_2_ce0,
        local_weights_0_2_q0,
        local_weights_1_0_address0,
        local_weights_1_0_ce0,
        local_weights_1_0_q0,
        local_weights_1_1_address0,
        local_weights_1_1_ce0,
        local_weights_1_1_q0,
        local_weights_1_2_address0,
        local_weights_1_2_ce0,
        local_weights_1_2_q0,
        local_weights_2_0_address0,
        local_weights_2_0_ce0,
        local_weights_2_0_q0,
        local_weights_2_1_address0,
        local_weights_2_1_ce0,
        local_weights_2_1_q0,
        local_weights_2_2_address0,
        local_weights_2_2_ce0,
        local_weights_2_2_q0,
        local_bias_address0,
        local_bias_ce0,
        local_bias_q0,
        output_buf_address0,
        output_buf_ce0,
        output_buf_we0,
        output_buf_d0
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_buf_0_0_address0;
output   input_buf_0_0_ce0;
input  [15:0] input_buf_0_0_q0;
output  [5:0] input_buf_0_1_address0;
output   input_buf_0_1_ce0;
input  [15:0] input_buf_0_1_q0;
output  [5:0] input_buf_0_2_address0;
output   input_buf_0_2_ce0;
input  [15:0] input_buf_0_2_q0;
output  [5:0] input_buf_1_0_address0;
output   input_buf_1_0_ce0;
input  [15:0] input_buf_1_0_q0;
output  [5:0] input_buf_1_1_address0;
output   input_buf_1_1_ce0;
input  [15:0] input_buf_1_1_q0;
output  [5:0] input_buf_1_2_address0;
output   input_buf_1_2_ce0;
input  [15:0] input_buf_1_2_q0;
output  [5:0] input_buf_2_0_address0;
output   input_buf_2_0_ce0;
input  [15:0] input_buf_2_0_q0;
output  [5:0] input_buf_2_1_address0;
output   input_buf_2_1_ce0;
input  [15:0] input_buf_2_1_q0;
output  [5:0] input_buf_2_2_address0;
output   input_buf_2_2_ce0;
input  [15:0] input_buf_2_2_q0;
output  [4:0] local_weights_0_0_address0;
output   local_weights_0_0_ce0;
input  [15:0] local_weights_0_0_q0;
output  [4:0] local_weights_0_1_address0;
output   local_weights_0_1_ce0;
input  [15:0] local_weights_0_1_q0;
output  [4:0] local_weights_0_2_address0;
output   local_weights_0_2_ce0;
input  [15:0] local_weights_0_2_q0;
output  [4:0] local_weights_1_0_address0;
output   local_weights_1_0_ce0;
input  [15:0] local_weights_1_0_q0;
output  [4:0] local_weights_1_1_address0;
output   local_weights_1_1_ce0;
input  [15:0] local_weights_1_1_q0;
output  [4:0] local_weights_1_2_address0;
output   local_weights_1_2_ce0;
input  [15:0] local_weights_1_2_q0;
output  [4:0] local_weights_2_0_address0;
output   local_weights_2_0_ce0;
input  [15:0] local_weights_2_0_q0;
output  [4:0] local_weights_2_1_address0;
output   local_weights_2_1_ce0;
input  [15:0] local_weights_2_1_q0;
output  [4:0] local_weights_2_2_address0;
output   local_weights_2_2_ce0;
input  [15:0] local_weights_2_2_q0;
output  [4:0] local_bias_address0;
output   local_bias_ce0;
input  [15:0] local_bias_q0;
output  [12:0] output_buf_address0;
output   output_buf_ce0;
output   output_buf_we0;
output  [14:0] output_buf_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] add_ln77_fu_309_p2;
reg   [5:0] add_ln77_reg_546;
wire    ap_CS_fsm_state2;
wire   [4:0] empty_fu_315_p1;
reg   [4:0] empty_reg_551;
wire   [27:0] sum_fu_333_p3;
reg   [27:0] sum_reg_606;
wire    ap_CS_fsm_state3;
reg   [15:0] local_weights_0_0_load_reg_611;
reg   [15:0] local_weights_0_1_load_reg_616;
reg   [15:0] local_weights_0_2_load_reg_621;
reg   [15:0] local_weights_1_0_load_reg_626;
reg   [15:0] local_weights_1_1_load_reg_631;
reg   [15:0] local_weights_1_2_load_reg_636;
reg   [15:0] local_weights_2_0_load_reg_641;
reg   [15:0] local_weights_2_1_load_reg_646;
reg   [15:0] local_weights_2_2_load_reg_651;
wire   [4:0] zext_ln79_fu_347_p1;
reg   [4:0] zext_ln79_reg_656;
wire    ap_CS_fsm_state8;
wire   [1:0] trunc_ln79_fu_371_p1;
reg   [1:0] trunc_ln79_reg_661;
wire    ap_CS_fsm_state11;
wire   [3:0] empty_62_fu_390_p1;
reg   [3:0] empty_62_reg_666;
wire   [4:0] sub_ln90_fu_444_p2;
reg   [4:0] sub_ln90_reg_671;
wire   [4:0] sub_ln90_1_fu_477_p2;
reg   [4:0] sub_ln90_1_reg_676;
wire   [4:0] sub_ln90_2_fu_509_p2;
reg   [4:0] sub_ln90_2_reg_681;
wire   [0:0] icmp_ln79_fu_516_p2;
reg   [0:0] icmp_ln79_reg_686;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_idle;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_ready;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_0_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_0_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_1_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_1_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_2_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_2_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_0_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_0_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_1_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_1_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_2_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_2_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_0_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_0_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_1_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_1_ce0;
wire   [5:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_2_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_2_ce0;
wire   [12:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_address0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_ce0;
wire    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_we0;
wire   [14:0] grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_d0;
reg   [3:0] i_reg_242;
wire    ap_CS_fsm_state12;
reg    grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start_reg;
wire   [31:0] oc_cast_cast_fu_319_p1;
wire   [0:0] icmp_ln77_fu_303_p2;
reg   [5:0] oc_fu_108;
reg    local_bias_ce0_local;
reg    local_weights_0_0_ce0_local;
reg    local_weights_0_1_ce0_local;
reg    local_weights_0_2_ce0_local;
reg    local_weights_1_0_ce0_local;
reg    local_weights_1_1_ce0_local;
reg    local_weights_1_2_ce0_local;
reg    local_weights_2_0_ce0_local;
reg    local_weights_2_1_ce0_local;
reg    local_weights_2_2_ce0_local;
wire   [2:0] grp_fu_341_p1;
wire    ap_CS_fsm_state4;
wire   [3:0] mul_ln79_fu_355_p0;
wire   [5:0] mul_ln79_fu_355_p1;
wire   [8:0] mul_ln79_fu_355_p2;
wire   [1:0] grp_fu_341_p2;
wire   [10:0] tmp_41_fu_376_p1;
wire  signed [10:0] grp_fu_526_p3;
wire   [4:0] empty_61_fu_385_p2;
wire   [4:0] mul_fu_398_p0;
wire   [6:0] mul_fu_398_p1;
wire   [10:0] mul_fu_398_p2;
wire   [2:0] tmp_fu_361_p4;
wire   [1:0] tmp_43_fu_414_p4;
wire   [3:0] tmp_44_fu_424_p3;
wire   [4:0] tmp_45_fu_432_p3;
wire   [4:0] zext_ln90_fu_440_p1;
wire   [3:0] tmp_42_fu_404_p4;
wire   [1:0] tmp_46_fu_451_p4;
wire   [4:0] tmp_48_fu_469_p3;
wire   [4:0] tmp_47_fu_461_p3;
wire   [10:0] tmp_49_fu_484_p1;
wire   [3:0] tmp_41_fu_376_p4;
wire   [1:0] tmp_49_fu_484_p4;
wire   [4:0] tmp_51_fu_501_p3;
wire   [4:0] tmp_50_fu_493_p3;
wire   [3:0] grp_fu_526_p0;
wire   [1:0] grp_fu_526_p1;
wire   [5:0] grp_fu_526_p2;
reg    grp_fu_341_ap_start;
wire    grp_fu_341_ap_done;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire   [4:0] grp_fu_526_p00;
wire   [10:0] mul_fu_398_p00;
wire   [8:0] mul_ln79_fu_355_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start_reg = 1'b0;
#0 oc_fu_108 = 6'd0;
end

cnn_top_convolution_func_2_Pipeline_VITIS_LOOP_81_3 grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start),
    .ap_done(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done),
    .ap_idle(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_idle),
    .ap_ready(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_ready),
    .mul_ln90_9(sub_ln90_reg_671),
    .input_buf_0_0_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_0_address0),
    .input_buf_0_0_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_0_ce0),
    .input_buf_0_0_q0(input_buf_0_0_q0),
    .mul_ln90_10(sub_ln90_1_reg_676),
    .mul_ln90_11(sub_ln90_2_reg_681),
    .input_buf_0_1_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_1_address0),
    .input_buf_0_1_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_1_ce0),
    .input_buf_0_1_q0(input_buf_0_1_q0),
    .input_buf_0_2_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_2_address0),
    .input_buf_0_2_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_2_ce0),
    .input_buf_0_2_q0(input_buf_0_2_q0),
    .input_buf_1_0_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_0_address0),
    .input_buf_1_0_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_0_ce0),
    .input_buf_1_0_q0(input_buf_1_0_q0),
    .input_buf_1_1_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_1_address0),
    .input_buf_1_1_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_1_ce0),
    .input_buf_1_1_q0(input_buf_1_1_q0),
    .input_buf_1_2_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_2_address0),
    .input_buf_1_2_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_2_ce0),
    .input_buf_1_2_q0(input_buf_1_2_q0),
    .input_buf_2_0_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_0_address0),
    .input_buf_2_0_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_0_ce0),
    .input_buf_2_0_q0(input_buf_2_0_q0),
    .input_buf_2_1_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_1_address0),
    .input_buf_2_1_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_1_ce0),
    .input_buf_2_1_q0(input_buf_2_1_q0),
    .input_buf_2_2_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_2_address0),
    .input_buf_2_2_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_2_ce0),
    .input_buf_2_2_q0(input_buf_2_2_q0),
    .empty_41(trunc_ln79_reg_661),
    .sext_ln90_15(local_weights_2_0_load_reg_641),
    .sext_ln90_16(local_weights_2_1_load_reg_646),
    .sext_ln90_17(local_weights_2_2_load_reg_651),
    .sext_ln90_1(local_weights_0_0_load_reg_611),
    .sext_ln90_2(local_weights_0_1_load_reg_616),
    .sext_ln90_11(local_weights_0_2_load_reg_621),
    .sext_ln90_12(local_weights_1_0_load_reg_626),
    .sext_ln90_13(local_weights_1_1_load_reg_631),
    .sext_ln90_14(local_weights_1_2_load_reg_636),
    .sum(sum_reg_606),
    .empty(empty_reg_551),
    .i(i_reg_242),
    .output_buf_address0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_address0),
    .output_buf_ce0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_ce0),
    .output_buf_we0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_we0),
    .output_buf_d0(grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_d0)
);

cnn_top_urem_4ns_3ns_2_8_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_seq_1_U136(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_341_ap_start),
    .done(grp_fu_341_ap_done),
    .din0(i_reg_242),
    .din1(grp_fu_341_p1),
    .ce(1'b1),
    .dout(grp_fu_341_p2)
);

cnn_top_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U137(
    .din0(mul_ln79_fu_355_p0),
    .din1(mul_ln79_fu_355_p1),
    .dout(mul_ln79_fu_355_p2)
);

cnn_top_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U138(
    .din0(mul_fu_398_p0),
    .din1(mul_fu_398_p1),
    .dout(mul_fu_398_p2)
);

cnn_top_am_addmul_4ns_2ns_6ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
am_addmul_4ns_2ns_6ns_11_4_1_U139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_526_p0),
    .din1(grp_fu_526_p1),
    .din2(grp_fu_526_p2),
    .ce(1'b1),
    .dout(grp_fu_526_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start_reg <= 1'b1;
        end else if ((grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_ready == 1'b1)) begin
            grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done == 1'b1) & (icmp_ln79_reg_686 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        i_reg_242 <= empty_62_reg_666;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_242 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oc_fu_108 <= 6'd0;
    end else if (((grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done == 1'b1) & (icmp_ln79_reg_686 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        oc_fu_108 <= add_ln77_reg_546;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln77_reg_546 <= add_ln77_fu_309_p2;
        empty_reg_551 <= empty_fu_315_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_62_reg_666 <= empty_62_fu_390_p1;
        icmp_ln79_reg_686 <= icmp_ln79_fu_516_p2;
        sub_ln90_1_reg_676[4 : 1] <= sub_ln90_1_fu_477_p2[4 : 1];
        sub_ln90_2_reg_681[4 : 1] <= sub_ln90_2_fu_509_p2[4 : 1];
        sub_ln90_reg_671[4 : 1] <= sub_ln90_fu_444_p2[4 : 1];
        trunc_ln79_reg_661 <= trunc_ln79_fu_371_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        local_weights_0_0_load_reg_611 <= local_weights_0_0_q0;
        local_weights_0_1_load_reg_616 <= local_weights_0_1_q0;
        local_weights_0_2_load_reg_621 <= local_weights_0_2_q0;
        local_weights_1_0_load_reg_626 <= local_weights_1_0_q0;
        local_weights_1_1_load_reg_631 <= local_weights_1_1_q0;
        local_weights_1_2_load_reg_636 <= local_weights_1_2_q0;
        local_weights_2_0_load_reg_641 <= local_weights_2_0_q0;
        local_weights_2_1_load_reg_646 <= local_weights_2_1_q0;
        local_weights_2_2_load_reg_651 <= local_weights_2_2_q0;
        sum_reg_606[27 : 12] <= sum_fu_333_p3[27 : 12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        zext_ln79_reg_656[3 : 0] <= zext_ln79_fu_347_p1[3 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln77_fu_303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln77_fu_303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_341_ap_start = 1'b1;
    end else begin
        grp_fu_341_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_bias_ce0_local = 1'b1;
    end else begin
        local_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_0_0_ce0_local = 1'b1;
    end else begin
        local_weights_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_0_1_ce0_local = 1'b1;
    end else begin
        local_weights_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_0_2_ce0_local = 1'b1;
    end else begin
        local_weights_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_1_0_ce0_local = 1'b1;
    end else begin
        local_weights_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_1_1_ce0_local = 1'b1;
    end else begin
        local_weights_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_1_2_ce0_local = 1'b1;
    end else begin
        local_weights_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_2_0_ce0_local = 1'b1;
    end else begin
        local_weights_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_2_1_ce0_local = 1'b1;
    end else begin
        local_weights_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_2_2_ce0_local = 1'b1;
    end else begin
        local_weights_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln77_fu_303_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done == 1'b1) & (icmp_ln79_reg_686 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_done == 1'b1) & (icmp_ln79_reg_686 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln77_fu_309_p2 = (oc_fu_108 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign empty_61_fu_385_p2 = (zext_ln79_reg_656 + 5'd1);

assign empty_62_fu_390_p1 = empty_61_fu_385_p2[3:0];

assign empty_fu_315_p1 = oc_fu_108[4:0];

assign grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_ap_start_reg;

assign grp_fu_341_p1 = 4'd3;

assign grp_fu_526_p0 = grp_fu_526_p00;

assign grp_fu_526_p00 = i_reg_242;

assign grp_fu_526_p1 = 5'd2;

assign grp_fu_526_p2 = 11'd43;

assign icmp_ln77_fu_303_p2 = ((oc_fu_108 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_516_p2 = ((empty_61_fu_385_p2 == 5'd16) ? 1'b1 : 1'b0);

assign input_buf_0_0_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_0_address0;

assign input_buf_0_0_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_0_ce0;

assign input_buf_0_1_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_1_address0;

assign input_buf_0_1_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_1_ce0;

assign input_buf_0_2_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_2_address0;

assign input_buf_0_2_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_0_2_ce0;

assign input_buf_1_0_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_0_address0;

assign input_buf_1_0_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_0_ce0;

assign input_buf_1_1_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_1_address0;

assign input_buf_1_1_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_1_ce0;

assign input_buf_1_2_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_2_address0;

assign input_buf_1_2_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_1_2_ce0;

assign input_buf_2_0_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_0_address0;

assign input_buf_2_0_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_0_ce0;

assign input_buf_2_1_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_1_address0;

assign input_buf_2_1_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_1_ce0;

assign input_buf_2_2_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_2_address0;

assign input_buf_2_2_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_input_buf_2_2_ce0;

assign local_bias_address0 = oc_cast_cast_fu_319_p1;

assign local_bias_ce0 = local_bias_ce0_local;

assign local_weights_0_0_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_0_0_ce0 = local_weights_0_0_ce0_local;

assign local_weights_0_1_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_0_1_ce0 = local_weights_0_1_ce0_local;

assign local_weights_0_2_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_0_2_ce0 = local_weights_0_2_ce0_local;

assign local_weights_1_0_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_1_0_ce0 = local_weights_1_0_ce0_local;

assign local_weights_1_1_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_1_1_ce0 = local_weights_1_1_ce0_local;

assign local_weights_1_2_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_1_2_ce0 = local_weights_1_2_ce0_local;

assign local_weights_2_0_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_2_0_ce0 = local_weights_2_0_ce0_local;

assign local_weights_2_1_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_2_1_ce0 = local_weights_2_1_ce0_local;

assign local_weights_2_2_address0 = oc_cast_cast_fu_319_p1;

assign local_weights_2_2_ce0 = local_weights_2_2_ce0_local;

assign mul_fu_398_p0 = mul_fu_398_p00;

assign mul_fu_398_p00 = empty_61_fu_385_p2;

assign mul_fu_398_p1 = 11'd43;

assign mul_ln79_fu_355_p0 = mul_ln79_fu_355_p00;

assign mul_ln79_fu_355_p00 = i_reg_242;

assign mul_ln79_fu_355_p1 = 9'd22;

assign oc_cast_cast_fu_319_p1 = empty_fu_315_p1;

assign output_buf_address0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_address0;

assign output_buf_ce0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_ce0;

assign output_buf_d0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_d0;

assign output_buf_we0 = grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254_output_buf_we0;

assign sub_ln90_1_fu_477_p2 = (tmp_48_fu_469_p3 - tmp_47_fu_461_p3);

assign sub_ln90_2_fu_509_p2 = (tmp_51_fu_501_p3 - tmp_50_fu_493_p3);

assign sub_ln90_fu_444_p2 = (tmp_45_fu_432_p3 - zext_ln90_fu_440_p1);

assign sum_fu_333_p3 = {{local_bias_q0}, {12'd0}};

assign tmp_41_fu_376_p1 = grp_fu_526_p3;

assign tmp_41_fu_376_p4 = {{tmp_41_fu_376_p1[10:7]}};

assign tmp_42_fu_404_p4 = {{mul_fu_398_p2[10:7]}};

assign tmp_43_fu_414_p4 = {{mul_ln79_fu_355_p2[7:6]}};

assign tmp_44_fu_424_p3 = {{tmp_fu_361_p4}, {1'd0}};

assign tmp_45_fu_432_p3 = {{tmp_43_fu_414_p4}, {3'd0}};

assign tmp_46_fu_451_p4 = {{mul_fu_398_p2[8:7]}};

assign tmp_47_fu_461_p3 = {{tmp_42_fu_404_p4}, {1'd0}};

assign tmp_48_fu_469_p3 = {{tmp_46_fu_451_p4}, {3'd0}};

assign tmp_49_fu_484_p1 = grp_fu_526_p3;

assign tmp_49_fu_484_p4 = {{tmp_49_fu_484_p1[8:7]}};

assign tmp_50_fu_493_p3 = {{tmp_41_fu_376_p4}, {1'd0}};

assign tmp_51_fu_501_p3 = {{tmp_49_fu_484_p4}, {3'd0}};

assign tmp_fu_361_p4 = {{mul_ln79_fu_355_p2[8:6]}};

assign trunc_ln79_fu_371_p1 = grp_fu_341_p2[1:0];

assign zext_ln79_fu_347_p1 = i_reg_242;

assign zext_ln90_fu_440_p1 = tmp_44_fu_424_p3;

always @ (posedge ap_clk) begin
    sum_reg_606[11:0] <= 12'b000000000000;
    zext_ln79_reg_656[4] <= 1'b0;
    sub_ln90_reg_671[0] <= 1'b0;
    sub_ln90_1_reg_676[0] <= 1'b0;
    sub_ln90_2_reg_681[0] <= 1'b0;
end

endmodule //cnn_top_convolution_func_2
