// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_top_compute_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        this_weights,
        m_axi_gmem3_0_AWVALID,
        m_axi_gmem3_0_AWREADY,
        m_axi_gmem3_0_AWADDR,
        m_axi_gmem3_0_AWID,
        m_axi_gmem3_0_AWLEN,
        m_axi_gmem3_0_AWSIZE,
        m_axi_gmem3_0_AWBURST,
        m_axi_gmem3_0_AWLOCK,
        m_axi_gmem3_0_AWCACHE,
        m_axi_gmem3_0_AWPROT,
        m_axi_gmem3_0_AWQOS,
        m_axi_gmem3_0_AWREGION,
        m_axi_gmem3_0_AWUSER,
        m_axi_gmem3_0_WVALID,
        m_axi_gmem3_0_WREADY,
        m_axi_gmem3_0_WDATA,
        m_axi_gmem3_0_WSTRB,
        m_axi_gmem3_0_WLAST,
        m_axi_gmem3_0_WID,
        m_axi_gmem3_0_WUSER,
        m_axi_gmem3_0_ARVALID,
        m_axi_gmem3_0_ARREADY,
        m_axi_gmem3_0_ARADDR,
        m_axi_gmem3_0_ARID,
        m_axi_gmem3_0_ARLEN,
        m_axi_gmem3_0_ARSIZE,
        m_axi_gmem3_0_ARBURST,
        m_axi_gmem3_0_ARLOCK,
        m_axi_gmem3_0_ARCACHE,
        m_axi_gmem3_0_ARPROT,
        m_axi_gmem3_0_ARQOS,
        m_axi_gmem3_0_ARREGION,
        m_axi_gmem3_0_ARUSER,
        m_axi_gmem3_0_RVALID,
        m_axi_gmem3_0_RREADY,
        m_axi_gmem3_0_RDATA,
        m_axi_gmem3_0_RLAST,
        m_axi_gmem3_0_RID,
        m_axi_gmem3_0_RFIFONUM,
        m_axi_gmem3_0_RUSER,
        m_axi_gmem3_0_RRESP,
        m_axi_gmem3_0_BVALID,
        m_axi_gmem3_0_BREADY,
        m_axi_gmem3_0_BRESP,
        m_axi_gmem3_0_BID,
        m_axi_gmem3_0_BUSER,
        this_bias,
        input_s_dout,
        input_s_empty_n,
        input_s_read,
        input_s_num_data_valid,
        input_s_fifo_cap,
        conv1_out_din,
        conv1_out_full_n,
        conv1_out_write,
        conv1_out_num_data_valid,
        conv1_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [31:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [15:0] m_axi_gmem2_0_WDATA;
output  [1:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [31:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [15:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [10:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [31:0] this_weights;
output   m_axi_gmem3_0_AWVALID;
input   m_axi_gmem3_0_AWREADY;
output  [31:0] m_axi_gmem3_0_AWADDR;
output  [0:0] m_axi_gmem3_0_AWID;
output  [31:0] m_axi_gmem3_0_AWLEN;
output  [2:0] m_axi_gmem3_0_AWSIZE;
output  [1:0] m_axi_gmem3_0_AWBURST;
output  [1:0] m_axi_gmem3_0_AWLOCK;
output  [3:0] m_axi_gmem3_0_AWCACHE;
output  [2:0] m_axi_gmem3_0_AWPROT;
output  [3:0] m_axi_gmem3_0_AWQOS;
output  [3:0] m_axi_gmem3_0_AWREGION;
output  [0:0] m_axi_gmem3_0_AWUSER;
output   m_axi_gmem3_0_WVALID;
input   m_axi_gmem3_0_WREADY;
output  [15:0] m_axi_gmem3_0_WDATA;
output  [1:0] m_axi_gmem3_0_WSTRB;
output   m_axi_gmem3_0_WLAST;
output  [0:0] m_axi_gmem3_0_WID;
output  [0:0] m_axi_gmem3_0_WUSER;
output   m_axi_gmem3_0_ARVALID;
input   m_axi_gmem3_0_ARREADY;
output  [31:0] m_axi_gmem3_0_ARADDR;
output  [0:0] m_axi_gmem3_0_ARID;
output  [31:0] m_axi_gmem3_0_ARLEN;
output  [2:0] m_axi_gmem3_0_ARSIZE;
output  [1:0] m_axi_gmem3_0_ARBURST;
output  [1:0] m_axi_gmem3_0_ARLOCK;
output  [3:0] m_axi_gmem3_0_ARCACHE;
output  [2:0] m_axi_gmem3_0_ARPROT;
output  [3:0] m_axi_gmem3_0_ARQOS;
output  [3:0] m_axi_gmem3_0_ARREGION;
output  [0:0] m_axi_gmem3_0_ARUSER;
input   m_axi_gmem3_0_RVALID;
output   m_axi_gmem3_0_RREADY;
input  [15:0] m_axi_gmem3_0_RDATA;
input   m_axi_gmem3_0_RLAST;
input  [0:0] m_axi_gmem3_0_RID;
input  [10:0] m_axi_gmem3_0_RFIFONUM;
input  [0:0] m_axi_gmem3_0_RUSER;
input  [1:0] m_axi_gmem3_0_RRESP;
input   m_axi_gmem3_0_BVALID;
output   m_axi_gmem3_0_BREADY;
input  [1:0] m_axi_gmem3_0_BRESP;
input  [0:0] m_axi_gmem3_0_BID;
input  [0:0] m_axi_gmem3_0_BUSER;
input  [31:0] this_bias;
input  [15:0] input_s_dout;
input   input_s_empty_n;
output   input_s_read;
input  [8:0] input_s_num_data_valid;
input  [8:0] input_s_fifo_cap;
output  [15:0] conv1_out_din;
input   conv1_out_full_n;
output   conv1_out_write;
input  [13:0] conv1_out_num_data_valid;
input  [13:0] conv1_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] this_bias_read_reg_225;
reg    ap_block_state1;
reg   [31:0] this_weights_read_reg_230;
reg   [5:0] input_buf_address0;
reg    input_buf_ce0;
reg    input_buf_we0;
wire   [15:0] input_buf_q0;
reg   [5:0] input_buf_1_address0;
reg    input_buf_1_ce0;
reg    input_buf_1_we0;
wire   [15:0] input_buf_1_q0;
reg   [5:0] input_buf_2_address0;
reg    input_buf_2_ce0;
reg    input_buf_2_we0;
wire   [15:0] input_buf_2_q0;
reg   [5:0] input_buf_3_address0;
reg    input_buf_3_ce0;
reg    input_buf_3_we0;
wire   [15:0] input_buf_3_q0;
reg   [5:0] input_buf_4_address0;
reg    input_buf_4_ce0;
reg    input_buf_4_we0;
wire   [15:0] input_buf_4_q0;
reg   [5:0] input_buf_5_address0;
reg    input_buf_5_ce0;
reg    input_buf_5_we0;
wire   [15:0] input_buf_5_q0;
reg   [5:0] input_buf_6_address0;
reg    input_buf_6_ce0;
reg    input_buf_6_we0;
wire   [15:0] input_buf_6_q0;
reg   [5:0] input_buf_7_address0;
reg    input_buf_7_ce0;
reg    input_buf_7_we0;
wire   [15:0] input_buf_7_q0;
reg   [5:0] input_buf_8_address0;
reg    input_buf_8_ce0;
reg    input_buf_8_we0;
wire   [15:0] input_buf_8_q0;
reg   [12:0] output_buf_address0;
reg    output_buf_ce0;
reg    output_buf_we0;
wire   [14:0] output_buf_q0;
reg   [4:0] local_weights_address0;
reg    local_weights_ce0;
reg    local_weights_we0;
wire   [15:0] local_weights_q0;
reg   [4:0] local_weights_1_address0;
reg    local_weights_1_ce0;
reg    local_weights_1_we0;
wire   [15:0] local_weights_1_q0;
reg   [4:0] local_weights_2_address0;
reg    local_weights_2_ce0;
reg    local_weights_2_we0;
wire   [15:0] local_weights_2_q0;
reg   [4:0] local_weights_3_address0;
reg    local_weights_3_ce0;
reg    local_weights_3_we0;
wire   [15:0] local_weights_3_q0;
reg   [4:0] local_weights_4_address0;
reg    local_weights_4_ce0;
reg    local_weights_4_we0;
wire   [15:0] local_weights_4_q0;
reg   [4:0] local_weights_5_address0;
reg    local_weights_5_ce0;
reg    local_weights_5_we0;
wire   [15:0] local_weights_5_q0;
reg   [4:0] local_weights_6_address0;
reg    local_weights_6_ce0;
reg    local_weights_6_we0;
wire   [15:0] local_weights_6_q0;
reg   [4:0] local_weights_7_address0;
reg    local_weights_7_ce0;
reg    local_weights_7_we0;
wire   [15:0] local_weights_7_q0;
reg   [4:0] local_weights_8_address0;
reg    local_weights_8_ce0;
reg    local_weights_8_we0;
wire   [15:0] local_weights_8_q0;
reg   [4:0] local_bias_address0;
reg    local_bias_ce0;
reg    local_bias_we0;
wire   [15:0] local_bias_q0;
wire    grp_load_params_func_2_fu_138_ap_start;
wire    grp_load_params_func_2_fu_138_ap_done;
wire    grp_load_params_func_2_fu_138_ap_idle;
wire    grp_load_params_func_2_fu_138_ap_ready;
wire    grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWVALID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWADDR;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWLEN;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWSIZE;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWBURST;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWLOCK;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWCACHE;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWPROT;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWQOS;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWREGION;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWUSER;
wire    grp_load_params_func_2_fu_138_m_axi_gmem2_0_WVALID;
wire   [15:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_WDATA;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_WSTRB;
wire    grp_load_params_func_2_fu_138_m_axi_gmem2_0_WLAST;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_WID;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_WUSER;
wire    grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARVALID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARADDR;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARLEN;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARSIZE;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARBURST;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARLOCK;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARCACHE;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARPROT;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARQOS;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARREGION;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARUSER;
wire    grp_load_params_func_2_fu_138_m_axi_gmem2_0_RREADY;
wire    grp_load_params_func_2_fu_138_m_axi_gmem2_0_BREADY;
wire    grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWVALID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWADDR;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWLEN;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWSIZE;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWBURST;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWLOCK;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWCACHE;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWPROT;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWQOS;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWREGION;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWUSER;
wire    grp_load_params_func_2_fu_138_m_axi_gmem3_0_WVALID;
wire   [15:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_WDATA;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_WSTRB;
wire    grp_load_params_func_2_fu_138_m_axi_gmem3_0_WLAST;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_WID;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_WUSER;
wire    grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARVALID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARADDR;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARID;
wire   [31:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARLEN;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARSIZE;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARBURST;
wire   [1:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARLOCK;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARCACHE;
wire   [2:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARPROT;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARQOS;
wire   [3:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARREGION;
wire   [0:0] grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARUSER;
wire    grp_load_params_func_2_fu_138_m_axi_gmem3_0_RREADY;
wire    grp_load_params_func_2_fu_138_m_axi_gmem3_0_BREADY;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_0_0_address0;
wire    grp_load_params_func_2_fu_138_local_weights_0_0_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_0_0_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_0_0_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_0_1_address0;
wire    grp_load_params_func_2_fu_138_local_weights_0_1_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_0_1_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_0_1_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_0_2_address0;
wire    grp_load_params_func_2_fu_138_local_weights_0_2_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_0_2_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_0_2_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_1_0_address0;
wire    grp_load_params_func_2_fu_138_local_weights_1_0_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_1_0_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_1_0_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_1_1_address0;
wire    grp_load_params_func_2_fu_138_local_weights_1_1_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_1_1_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_1_1_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_1_2_address0;
wire    grp_load_params_func_2_fu_138_local_weights_1_2_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_1_2_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_1_2_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_2_0_address0;
wire    grp_load_params_func_2_fu_138_local_weights_2_0_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_2_0_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_2_0_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_2_1_address0;
wire    grp_load_params_func_2_fu_138_local_weights_2_1_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_2_1_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_2_1_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_weights_2_2_address0;
wire    grp_load_params_func_2_fu_138_local_weights_2_2_ce0;
wire    grp_load_params_func_2_fu_138_local_weights_2_2_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_weights_2_2_d0;
wire   [4:0] grp_load_params_func_2_fu_138_local_bias_address0;
wire    grp_load_params_func_2_fu_138_local_bias_ce0;
wire    grp_load_params_func_2_fu_138_local_bias_we0;
wire   [15:0] grp_load_params_func_2_fu_138_local_bias_d0;
wire    grp_prepare_input_buf_func_2_fu_170_ap_start;
wire    grp_prepare_input_buf_func_2_fu_170_ap_done;
wire    grp_prepare_input_buf_func_2_fu_170_ap_idle;
wire    grp_prepare_input_buf_func_2_fu_170_ap_ready;
wire    grp_prepare_input_buf_func_2_fu_170_input_s_read;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_d0;
wire   [5:0] grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_address0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_ce0;
wire    grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_we0;
wire   [15:0] grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_d0;
wire    grp_convolution_func_2_fu_194_ap_start;
wire    grp_convolution_func_2_fu_194_ap_done;
wire    grp_convolution_func_2_fu_194_ap_idle;
wire    grp_convolution_func_2_fu_194_ap_ready;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_0_0_address0;
wire    grp_convolution_func_2_fu_194_input_buf_0_0_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_0_1_address0;
wire    grp_convolution_func_2_fu_194_input_buf_0_1_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_0_2_address0;
wire    grp_convolution_func_2_fu_194_input_buf_0_2_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_1_0_address0;
wire    grp_convolution_func_2_fu_194_input_buf_1_0_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_1_1_address0;
wire    grp_convolution_func_2_fu_194_input_buf_1_1_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_1_2_address0;
wire    grp_convolution_func_2_fu_194_input_buf_1_2_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_2_0_address0;
wire    grp_convolution_func_2_fu_194_input_buf_2_0_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_2_1_address0;
wire    grp_convolution_func_2_fu_194_input_buf_2_1_ce0;
wire   [5:0] grp_convolution_func_2_fu_194_input_buf_2_2_address0;
wire    grp_convolution_func_2_fu_194_input_buf_2_2_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_0_0_address0;
wire    grp_convolution_func_2_fu_194_local_weights_0_0_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_0_1_address0;
wire    grp_convolution_func_2_fu_194_local_weights_0_1_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_0_2_address0;
wire    grp_convolution_func_2_fu_194_local_weights_0_2_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_1_0_address0;
wire    grp_convolution_func_2_fu_194_local_weights_1_0_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_1_1_address0;
wire    grp_convolution_func_2_fu_194_local_weights_1_1_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_1_2_address0;
wire    grp_convolution_func_2_fu_194_local_weights_1_2_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_2_0_address0;
wire    grp_convolution_func_2_fu_194_local_weights_2_0_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_2_1_address0;
wire    grp_convolution_func_2_fu_194_local_weights_2_1_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_weights_2_2_address0;
wire    grp_convolution_func_2_fu_194_local_weights_2_2_ce0;
wire   [4:0] grp_convolution_func_2_fu_194_local_bias_address0;
wire    grp_convolution_func_2_fu_194_local_bias_ce0;
wire   [12:0] grp_convolution_func_2_fu_194_output_buf_address0;
wire    grp_convolution_func_2_fu_194_output_buf_ce0;
wire    grp_convolution_func_2_fu_194_output_buf_we0;
wire   [14:0] grp_convolution_func_2_fu_194_output_buf_d0;
wire    grp_write_output_func_2_fu_218_ap_start;
wire    grp_write_output_func_2_fu_218_ap_done;
wire    grp_write_output_func_2_fu_218_ap_idle;
wire    grp_write_output_func_2_fu_218_ap_ready;
wire   [15:0] grp_write_output_func_2_fu_218_conv1_out_din;
wire    grp_write_output_func_2_fu_218_conv1_out_write;
wire   [12:0] grp_write_output_func_2_fu_218_output_buf_address0;
wire    grp_write_output_func_2_fu_218_output_buf_ce0;
reg    grp_load_params_func_2_fu_138_ap_start_reg;
reg    ap_block_state1_ignore_call26;
wire    ap_CS_fsm_state2;
reg    grp_prepare_input_buf_func_2_fu_170_ap_start_reg;
reg    ap_block_state1_ignore_call27;
reg    grp_convolution_func_2_fu_194_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_write_output_func_2_fu_218_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_load_params_func_2_fu_138_ap_start_reg = 1'b0;
#0 grp_prepare_input_buf_func_2_fu_170_ap_start_reg = 1'b0;
#0 grp_convolution_func_2_fu_194_ap_start_reg = 1'b0;
#0 grp_write_output_func_2_fu_218_ap_start_reg = 1'b0;
end

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_address0),
    .ce0(input_buf_ce0),
    .we0(input_buf_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_d0),
    .q0(input_buf_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_1_address0),
    .ce0(input_buf_1_ce0),
    .we0(input_buf_1_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_d0),
    .q0(input_buf_1_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_2_address0),
    .ce0(input_buf_2_ce0),
    .we0(input_buf_2_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_d0),
    .q0(input_buf_2_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_3_address0),
    .ce0(input_buf_3_ce0),
    .we0(input_buf_3_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_d0),
    .q0(input_buf_3_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_4_address0),
    .ce0(input_buf_4_ce0),
    .we0(input_buf_4_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_d0),
    .q0(input_buf_4_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_5_address0),
    .ce0(input_buf_5_ce0),
    .we0(input_buf_5_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_d0),
    .q0(input_buf_5_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_6_address0),
    .ce0(input_buf_6_ce0),
    .we0(input_buf_6_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_d0),
    .q0(input_buf_6_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_7_address0),
    .ce0(input_buf_7_ce0),
    .we0(input_buf_7_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_d0),
    .q0(input_buf_7_q0)
);

cnn_top_compute_4_input_buf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
input_buf_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_buf_8_address0),
    .ce0(input_buf_8_ce0),
    .we0(input_buf_8_we0),
    .d0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_d0),
    .q0(input_buf_8_q0)
);

cnn_top_compute_4_output_buf_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 8192 ),
    .AddressWidth( 13 ))
output_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(output_buf_address0),
    .ce0(output_buf_ce0),
    .we0(output_buf_we0),
    .d0(grp_convolution_func_2_fu_194_output_buf_d0),
    .q0(output_buf_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_address0),
    .ce0(local_weights_ce0),
    .we0(local_weights_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_0_0_d0),
    .q0(local_weights_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_1_address0),
    .ce0(local_weights_1_ce0),
    .we0(local_weights_1_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_0_1_d0),
    .q0(local_weights_1_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_2_address0),
    .ce0(local_weights_2_ce0),
    .we0(local_weights_2_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_0_2_d0),
    .q0(local_weights_2_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_3_address0),
    .ce0(local_weights_3_ce0),
    .we0(local_weights_3_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_1_0_d0),
    .q0(local_weights_3_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_4_address0),
    .ce0(local_weights_4_ce0),
    .we0(local_weights_4_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_1_1_d0),
    .q0(local_weights_4_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_5_address0),
    .ce0(local_weights_5_ce0),
    .we0(local_weights_5_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_1_2_d0),
    .q0(local_weights_5_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_6_address0),
    .ce0(local_weights_6_ce0),
    .we0(local_weights_6_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_2_0_d0),
    .q0(local_weights_6_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_7_address0),
    .ce0(local_weights_7_ce0),
    .we0(local_weights_7_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_2_1_d0),
    .q0(local_weights_7_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_weights_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_weights_8_address0),
    .ce0(local_weights_8_ce0),
    .we0(local_weights_8_we0),
    .d0(grp_load_params_func_2_fu_138_local_weights_2_2_d0),
    .q0(local_weights_8_q0)
);

cnn_top_compute_4_local_weights_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
local_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(local_bias_address0),
    .ce0(local_bias_ce0),
    .we0(local_bias_we0),
    .d0(grp_load_params_func_2_fu_138_local_bias_d0),
    .q0(local_bias_q0)
);

cnn_top_load_params_func_2 grp_load_params_func_2_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_params_func_2_fu_138_ap_start),
    .ap_done(grp_load_params_func_2_fu_138_ap_done),
    .ap_idle(grp_load_params_func_2_fu_138_ap_idle),
    .ap_ready(grp_load_params_func_2_fu_138_ap_ready),
    .m_axi_gmem2_0_AWVALID(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(grp_load_params_func_2_fu_138_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(grp_load_params_func_2_fu_138_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(grp_load_params_func_2_fu_138_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(grp_load_params_func_2_fu_138_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(grp_load_params_func_2_fu_138_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(grp_load_params_func_2_fu_138_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(grp_load_params_func_2_fu_138_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(m_axi_gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(m_axi_gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(grp_load_params_func_2_fu_138_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(m_axi_gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(m_axi_gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(m_axi_gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(m_axi_gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(m_axi_gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(m_axi_gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(grp_load_params_func_2_fu_138_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .this_weights(this_weights_read_reg_230),
    .m_axi_gmem3_0_AWVALID(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWVALID),
    .m_axi_gmem3_0_AWREADY(1'b0),
    .m_axi_gmem3_0_AWADDR(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWADDR),
    .m_axi_gmem3_0_AWID(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWID),
    .m_axi_gmem3_0_AWLEN(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWLEN),
    .m_axi_gmem3_0_AWSIZE(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWSIZE),
    .m_axi_gmem3_0_AWBURST(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWBURST),
    .m_axi_gmem3_0_AWLOCK(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWLOCK),
    .m_axi_gmem3_0_AWCACHE(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWCACHE),
    .m_axi_gmem3_0_AWPROT(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWPROT),
    .m_axi_gmem3_0_AWQOS(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWQOS),
    .m_axi_gmem3_0_AWREGION(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWREGION),
    .m_axi_gmem3_0_AWUSER(grp_load_params_func_2_fu_138_m_axi_gmem3_0_AWUSER),
    .m_axi_gmem3_0_WVALID(grp_load_params_func_2_fu_138_m_axi_gmem3_0_WVALID),
    .m_axi_gmem3_0_WREADY(1'b0),
    .m_axi_gmem3_0_WDATA(grp_load_params_func_2_fu_138_m_axi_gmem3_0_WDATA),
    .m_axi_gmem3_0_WSTRB(grp_load_params_func_2_fu_138_m_axi_gmem3_0_WSTRB),
    .m_axi_gmem3_0_WLAST(grp_load_params_func_2_fu_138_m_axi_gmem3_0_WLAST),
    .m_axi_gmem3_0_WID(grp_load_params_func_2_fu_138_m_axi_gmem3_0_WID),
    .m_axi_gmem3_0_WUSER(grp_load_params_func_2_fu_138_m_axi_gmem3_0_WUSER),
    .m_axi_gmem3_0_ARVALID(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARVALID),
    .m_axi_gmem3_0_ARREADY(m_axi_gmem3_0_ARREADY),
    .m_axi_gmem3_0_ARADDR(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARADDR),
    .m_axi_gmem3_0_ARID(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARID),
    .m_axi_gmem3_0_ARLEN(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARLEN),
    .m_axi_gmem3_0_ARSIZE(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARSIZE),
    .m_axi_gmem3_0_ARBURST(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARBURST),
    .m_axi_gmem3_0_ARLOCK(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARLOCK),
    .m_axi_gmem3_0_ARCACHE(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARCACHE),
    .m_axi_gmem3_0_ARPROT(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARPROT),
    .m_axi_gmem3_0_ARQOS(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARQOS),
    .m_axi_gmem3_0_ARREGION(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARREGION),
    .m_axi_gmem3_0_ARUSER(grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARUSER),
    .m_axi_gmem3_0_RVALID(m_axi_gmem3_0_RVALID),
    .m_axi_gmem3_0_RREADY(grp_load_params_func_2_fu_138_m_axi_gmem3_0_RREADY),
    .m_axi_gmem3_0_RDATA(m_axi_gmem3_0_RDATA),
    .m_axi_gmem3_0_RLAST(m_axi_gmem3_0_RLAST),
    .m_axi_gmem3_0_RID(m_axi_gmem3_0_RID),
    .m_axi_gmem3_0_RFIFONUM(m_axi_gmem3_0_RFIFONUM),
    .m_axi_gmem3_0_RUSER(m_axi_gmem3_0_RUSER),
    .m_axi_gmem3_0_RRESP(m_axi_gmem3_0_RRESP),
    .m_axi_gmem3_0_BVALID(1'b0),
    .m_axi_gmem3_0_BREADY(grp_load_params_func_2_fu_138_m_axi_gmem3_0_BREADY),
    .m_axi_gmem3_0_BRESP(2'd0),
    .m_axi_gmem3_0_BID(1'd0),
    .m_axi_gmem3_0_BUSER(1'd0),
    .this_bias(this_bias_read_reg_225),
    .local_weights_0_0_address0(grp_load_params_func_2_fu_138_local_weights_0_0_address0),
    .local_weights_0_0_ce0(grp_load_params_func_2_fu_138_local_weights_0_0_ce0),
    .local_weights_0_0_we0(grp_load_params_func_2_fu_138_local_weights_0_0_we0),
    .local_weights_0_0_d0(grp_load_params_func_2_fu_138_local_weights_0_0_d0),
    .local_weights_0_1_address0(grp_load_params_func_2_fu_138_local_weights_0_1_address0),
    .local_weights_0_1_ce0(grp_load_params_func_2_fu_138_local_weights_0_1_ce0),
    .local_weights_0_1_we0(grp_load_params_func_2_fu_138_local_weights_0_1_we0),
    .local_weights_0_1_d0(grp_load_params_func_2_fu_138_local_weights_0_1_d0),
    .local_weights_0_2_address0(grp_load_params_func_2_fu_138_local_weights_0_2_address0),
    .local_weights_0_2_ce0(grp_load_params_func_2_fu_138_local_weights_0_2_ce0),
    .local_weights_0_2_we0(grp_load_params_func_2_fu_138_local_weights_0_2_we0),
    .local_weights_0_2_d0(grp_load_params_func_2_fu_138_local_weights_0_2_d0),
    .local_weights_1_0_address0(grp_load_params_func_2_fu_138_local_weights_1_0_address0),
    .local_weights_1_0_ce0(grp_load_params_func_2_fu_138_local_weights_1_0_ce0),
    .local_weights_1_0_we0(grp_load_params_func_2_fu_138_local_weights_1_0_we0),
    .local_weights_1_0_d0(grp_load_params_func_2_fu_138_local_weights_1_0_d0),
    .local_weights_1_1_address0(grp_load_params_func_2_fu_138_local_weights_1_1_address0),
    .local_weights_1_1_ce0(grp_load_params_func_2_fu_138_local_weights_1_1_ce0),
    .local_weights_1_1_we0(grp_load_params_func_2_fu_138_local_weights_1_1_we0),
    .local_weights_1_1_d0(grp_load_params_func_2_fu_138_local_weights_1_1_d0),
    .local_weights_1_2_address0(grp_load_params_func_2_fu_138_local_weights_1_2_address0),
    .local_weights_1_2_ce0(grp_load_params_func_2_fu_138_local_weights_1_2_ce0),
    .local_weights_1_2_we0(grp_load_params_func_2_fu_138_local_weights_1_2_we0),
    .local_weights_1_2_d0(grp_load_params_func_2_fu_138_local_weights_1_2_d0),
    .local_weights_2_0_address0(grp_load_params_func_2_fu_138_local_weights_2_0_address0),
    .local_weights_2_0_ce0(grp_load_params_func_2_fu_138_local_weights_2_0_ce0),
    .local_weights_2_0_we0(grp_load_params_func_2_fu_138_local_weights_2_0_we0),
    .local_weights_2_0_d0(grp_load_params_func_2_fu_138_local_weights_2_0_d0),
    .local_weights_2_1_address0(grp_load_params_func_2_fu_138_local_weights_2_1_address0),
    .local_weights_2_1_ce0(grp_load_params_func_2_fu_138_local_weights_2_1_ce0),
    .local_weights_2_1_we0(grp_load_params_func_2_fu_138_local_weights_2_1_we0),
    .local_weights_2_1_d0(grp_load_params_func_2_fu_138_local_weights_2_1_d0),
    .local_weights_2_2_address0(grp_load_params_func_2_fu_138_local_weights_2_2_address0),
    .local_weights_2_2_ce0(grp_load_params_func_2_fu_138_local_weights_2_2_ce0),
    .local_weights_2_2_we0(grp_load_params_func_2_fu_138_local_weights_2_2_we0),
    .local_weights_2_2_d0(grp_load_params_func_2_fu_138_local_weights_2_2_d0),
    .local_bias_address0(grp_load_params_func_2_fu_138_local_bias_address0),
    .local_bias_ce0(grp_load_params_func_2_fu_138_local_bias_ce0),
    .local_bias_we0(grp_load_params_func_2_fu_138_local_bias_we0),
    .local_bias_d0(grp_load_params_func_2_fu_138_local_bias_d0)
);

cnn_top_prepare_input_buf_func_2 grp_prepare_input_buf_func_2_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_prepare_input_buf_func_2_fu_170_ap_start),
    .ap_done(grp_prepare_input_buf_func_2_fu_170_ap_done),
    .ap_idle(grp_prepare_input_buf_func_2_fu_170_ap_idle),
    .ap_ready(grp_prepare_input_buf_func_2_fu_170_ap_ready),
    .input_s_dout(input_s_dout),
    .input_s_empty_n(input_s_empty_n),
    .input_s_read(grp_prepare_input_buf_func_2_fu_170_input_s_read),
    .input_s_num_data_valid(9'd0),
    .input_s_fifo_cap(9'd0),
    .input_buf_0_0_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_address0),
    .input_buf_0_0_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_ce0),
    .input_buf_0_0_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_we0),
    .input_buf_0_0_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_d0),
    .input_buf_0_1_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_address0),
    .input_buf_0_1_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_ce0),
    .input_buf_0_1_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_we0),
    .input_buf_0_1_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_d0),
    .input_buf_0_2_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_address0),
    .input_buf_0_2_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_ce0),
    .input_buf_0_2_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_we0),
    .input_buf_0_2_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_d0),
    .input_buf_1_0_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_address0),
    .input_buf_1_0_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_ce0),
    .input_buf_1_0_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_we0),
    .input_buf_1_0_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_d0),
    .input_buf_1_1_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_address0),
    .input_buf_1_1_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_ce0),
    .input_buf_1_1_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_we0),
    .input_buf_1_1_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_d0),
    .input_buf_1_2_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_address0),
    .input_buf_1_2_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_ce0),
    .input_buf_1_2_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_we0),
    .input_buf_1_2_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_d0),
    .input_buf_2_0_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_address0),
    .input_buf_2_0_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_ce0),
    .input_buf_2_0_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_we0),
    .input_buf_2_0_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_d0),
    .input_buf_2_1_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_address0),
    .input_buf_2_1_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_ce0),
    .input_buf_2_1_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_we0),
    .input_buf_2_1_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_d0),
    .input_buf_2_2_address0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_address0),
    .input_buf_2_2_ce0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_ce0),
    .input_buf_2_2_we0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_we0),
    .input_buf_2_2_d0(grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_d0)
);

cnn_top_convolution_func_2 grp_convolution_func_2_fu_194(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_convolution_func_2_fu_194_ap_start),
    .ap_done(grp_convolution_func_2_fu_194_ap_done),
    .ap_idle(grp_convolution_func_2_fu_194_ap_idle),
    .ap_ready(grp_convolution_func_2_fu_194_ap_ready),
    .input_buf_0_0_address0(grp_convolution_func_2_fu_194_input_buf_0_0_address0),
    .input_buf_0_0_ce0(grp_convolution_func_2_fu_194_input_buf_0_0_ce0),
    .input_buf_0_0_q0(input_buf_q0),
    .input_buf_0_1_address0(grp_convolution_func_2_fu_194_input_buf_0_1_address0),
    .input_buf_0_1_ce0(grp_convolution_func_2_fu_194_input_buf_0_1_ce0),
    .input_buf_0_1_q0(input_buf_1_q0),
    .input_buf_0_2_address0(grp_convolution_func_2_fu_194_input_buf_0_2_address0),
    .input_buf_0_2_ce0(grp_convolution_func_2_fu_194_input_buf_0_2_ce0),
    .input_buf_0_2_q0(input_buf_2_q0),
    .input_buf_1_0_address0(grp_convolution_func_2_fu_194_input_buf_1_0_address0),
    .input_buf_1_0_ce0(grp_convolution_func_2_fu_194_input_buf_1_0_ce0),
    .input_buf_1_0_q0(input_buf_3_q0),
    .input_buf_1_1_address0(grp_convolution_func_2_fu_194_input_buf_1_1_address0),
    .input_buf_1_1_ce0(grp_convolution_func_2_fu_194_input_buf_1_1_ce0),
    .input_buf_1_1_q0(input_buf_4_q0),
    .input_buf_1_2_address0(grp_convolution_func_2_fu_194_input_buf_1_2_address0),
    .input_buf_1_2_ce0(grp_convolution_func_2_fu_194_input_buf_1_2_ce0),
    .input_buf_1_2_q0(input_buf_5_q0),
    .input_buf_2_0_address0(grp_convolution_func_2_fu_194_input_buf_2_0_address0),
    .input_buf_2_0_ce0(grp_convolution_func_2_fu_194_input_buf_2_0_ce0),
    .input_buf_2_0_q0(input_buf_6_q0),
    .input_buf_2_1_address0(grp_convolution_func_2_fu_194_input_buf_2_1_address0),
    .input_buf_2_1_ce0(grp_convolution_func_2_fu_194_input_buf_2_1_ce0),
    .input_buf_2_1_q0(input_buf_7_q0),
    .input_buf_2_2_address0(grp_convolution_func_2_fu_194_input_buf_2_2_address0),
    .input_buf_2_2_ce0(grp_convolution_func_2_fu_194_input_buf_2_2_ce0),
    .input_buf_2_2_q0(input_buf_8_q0),
    .local_weights_0_0_address0(grp_convolution_func_2_fu_194_local_weights_0_0_address0),
    .local_weights_0_0_ce0(grp_convolution_func_2_fu_194_local_weights_0_0_ce0),
    .local_weights_0_0_q0(local_weights_q0),
    .local_weights_0_1_address0(grp_convolution_func_2_fu_194_local_weights_0_1_address0),
    .local_weights_0_1_ce0(grp_convolution_func_2_fu_194_local_weights_0_1_ce0),
    .local_weights_0_1_q0(local_weights_1_q0),
    .local_weights_0_2_address0(grp_convolution_func_2_fu_194_local_weights_0_2_address0),
    .local_weights_0_2_ce0(grp_convolution_func_2_fu_194_local_weights_0_2_ce0),
    .local_weights_0_2_q0(local_weights_2_q0),
    .local_weights_1_0_address0(grp_convolution_func_2_fu_194_local_weights_1_0_address0),
    .local_weights_1_0_ce0(grp_convolution_func_2_fu_194_local_weights_1_0_ce0),
    .local_weights_1_0_q0(local_weights_3_q0),
    .local_weights_1_1_address0(grp_convolution_func_2_fu_194_local_weights_1_1_address0),
    .local_weights_1_1_ce0(grp_convolution_func_2_fu_194_local_weights_1_1_ce0),
    .local_weights_1_1_q0(local_weights_4_q0),
    .local_weights_1_2_address0(grp_convolution_func_2_fu_194_local_weights_1_2_address0),
    .local_weights_1_2_ce0(grp_convolution_func_2_fu_194_local_weights_1_2_ce0),
    .local_weights_1_2_q0(local_weights_5_q0),
    .local_weights_2_0_address0(grp_convolution_func_2_fu_194_local_weights_2_0_address0),
    .local_weights_2_0_ce0(grp_convolution_func_2_fu_194_local_weights_2_0_ce0),
    .local_weights_2_0_q0(local_weights_6_q0),
    .local_weights_2_1_address0(grp_convolution_func_2_fu_194_local_weights_2_1_address0),
    .local_weights_2_1_ce0(grp_convolution_func_2_fu_194_local_weights_2_1_ce0),
    .local_weights_2_1_q0(local_weights_7_q0),
    .local_weights_2_2_address0(grp_convolution_func_2_fu_194_local_weights_2_2_address0),
    .local_weights_2_2_ce0(grp_convolution_func_2_fu_194_local_weights_2_2_ce0),
    .local_weights_2_2_q0(local_weights_8_q0),
    .local_bias_address0(grp_convolution_func_2_fu_194_local_bias_address0),
    .local_bias_ce0(grp_convolution_func_2_fu_194_local_bias_ce0),
    .local_bias_q0(local_bias_q0),
    .output_buf_address0(grp_convolution_func_2_fu_194_output_buf_address0),
    .output_buf_ce0(grp_convolution_func_2_fu_194_output_buf_ce0),
    .output_buf_we0(grp_convolution_func_2_fu_194_output_buf_we0),
    .output_buf_d0(grp_convolution_func_2_fu_194_output_buf_d0)
);

cnn_top_write_output_func_2 grp_write_output_func_2_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_output_func_2_fu_218_ap_start),
    .ap_done(grp_write_output_func_2_fu_218_ap_done),
    .ap_idle(grp_write_output_func_2_fu_218_ap_idle),
    .ap_ready(grp_write_output_func_2_fu_218_ap_ready),
    .conv1_out_din(grp_write_output_func_2_fu_218_conv1_out_din),
    .conv1_out_full_n(conv1_out_full_n),
    .conv1_out_write(grp_write_output_func_2_fu_218_conv1_out_write),
    .conv1_out_num_data_valid(14'd0),
    .conv1_out_fifo_cap(14'd0),
    .output_buf_address0(grp_write_output_func_2_fu_218_output_buf_address0),
    .output_buf_ce0(grp_write_output_func_2_fu_218_output_buf_ce0),
    .output_buf_q0(output_buf_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_write_output_func_2_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_convolution_func_2_fu_194_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_convolution_func_2_fu_194_ap_start_reg <= 1'b1;
        end else if ((grp_convolution_func_2_fu_194_ap_ready == 1'b1)) begin
            grp_convolution_func_2_fu_194_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_params_func_2_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call26))) begin
            grp_load_params_func_2_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_load_params_func_2_fu_138_ap_ready == 1'b1)) begin
            grp_load_params_func_2_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_prepare_input_buf_func_2_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call27))) begin
            grp_prepare_input_buf_func_2_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_prepare_input_buf_func_2_fu_170_ap_ready == 1'b1)) begin
            grp_prepare_input_buf_func_2_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_output_func_2_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_write_output_func_2_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_write_output_func_2_fu_218_ap_ready == 1'b1)) begin
            grp_write_output_func_2_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        this_bias_read_reg_225 <= this_bias;
        this_weights_read_reg_230 <= this_weights;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_convolution_func_2_fu_194_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_write_output_func_2_fu_218_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_output_func_2_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_output_func_2_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_address0 = grp_convolution_func_2_fu_194_input_buf_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_address0;
    end else begin
        input_buf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_1_ce0 = grp_convolution_func_2_fu_194_input_buf_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_ce0;
    end else begin
        input_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_1_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_1_we0;
    end else begin
        input_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_address0 = grp_convolution_func_2_fu_194_input_buf_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_address0;
    end else begin
        input_buf_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_2_ce0 = grp_convolution_func_2_fu_194_input_buf_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_ce0;
    end else begin
        input_buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_2_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_2_we0;
    end else begin
        input_buf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_3_address0 = grp_convolution_func_2_fu_194_input_buf_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_3_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_address0;
    end else begin
        input_buf_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_3_ce0 = grp_convolution_func_2_fu_194_input_buf_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_3_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_ce0;
    end else begin
        input_buf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_3_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_0_we0;
    end else begin
        input_buf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_4_address0 = grp_convolution_func_2_fu_194_input_buf_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_4_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_address0;
    end else begin
        input_buf_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_4_ce0 = grp_convolution_func_2_fu_194_input_buf_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_4_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_ce0;
    end else begin
        input_buf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_4_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_1_we0;
    end else begin
        input_buf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_5_address0 = grp_convolution_func_2_fu_194_input_buf_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_5_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_address0;
    end else begin
        input_buf_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_5_ce0 = grp_convolution_func_2_fu_194_input_buf_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_5_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_ce0;
    end else begin
        input_buf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_5_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_1_2_we0;
    end else begin
        input_buf_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_6_address0 = grp_convolution_func_2_fu_194_input_buf_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_6_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_address0;
    end else begin
        input_buf_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_6_ce0 = grp_convolution_func_2_fu_194_input_buf_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_6_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_ce0;
    end else begin
        input_buf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_6_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_0_we0;
    end else begin
        input_buf_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_7_address0 = grp_convolution_func_2_fu_194_input_buf_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_7_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_address0;
    end else begin
        input_buf_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_7_ce0 = grp_convolution_func_2_fu_194_input_buf_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_7_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_ce0;
    end else begin
        input_buf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_7_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_1_we0;
    end else begin
        input_buf_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_8_address0 = grp_convolution_func_2_fu_194_input_buf_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_8_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_address0;
    end else begin
        input_buf_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_8_ce0 = grp_convolution_func_2_fu_194_input_buf_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_8_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_ce0;
    end else begin
        input_buf_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_8_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_2_2_we0;
    end else begin
        input_buf_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_address0 = grp_convolution_func_2_fu_194_input_buf_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_address0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_address0;
    end else begin
        input_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_buf_ce0 = grp_convolution_func_2_fu_194_input_buf_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_ce0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_ce0;
    end else begin
        input_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_buf_we0 = grp_prepare_input_buf_func_2_fu_170_input_buf_0_0_we0;
    end else begin
        input_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_bias_address0 = grp_convolution_func_2_fu_194_local_bias_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_bias_address0 = grp_load_params_func_2_fu_138_local_bias_address0;
    end else begin
        local_bias_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_bias_ce0 = grp_convolution_func_2_fu_194_local_bias_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_bias_ce0 = grp_load_params_func_2_fu_138_local_bias_ce0;
    end else begin
        local_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_bias_we0 = grp_load_params_func_2_fu_138_local_bias_we0;
    end else begin
        local_bias_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_1_address0 = grp_convolution_func_2_fu_194_local_weights_0_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_1_address0 = grp_load_params_func_2_fu_138_local_weights_0_1_address0;
    end else begin
        local_weights_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_1_ce0 = grp_convolution_func_2_fu_194_local_weights_0_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_1_ce0 = grp_load_params_func_2_fu_138_local_weights_0_1_ce0;
    end else begin
        local_weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_1_we0 = grp_load_params_func_2_fu_138_local_weights_0_1_we0;
    end else begin
        local_weights_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_2_address0 = grp_convolution_func_2_fu_194_local_weights_0_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_2_address0 = grp_load_params_func_2_fu_138_local_weights_0_2_address0;
    end else begin
        local_weights_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_2_ce0 = grp_convolution_func_2_fu_194_local_weights_0_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_2_ce0 = grp_load_params_func_2_fu_138_local_weights_0_2_ce0;
    end else begin
        local_weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_2_we0 = grp_load_params_func_2_fu_138_local_weights_0_2_we0;
    end else begin
        local_weights_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_3_address0 = grp_convolution_func_2_fu_194_local_weights_1_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_3_address0 = grp_load_params_func_2_fu_138_local_weights_1_0_address0;
    end else begin
        local_weights_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_3_ce0 = grp_convolution_func_2_fu_194_local_weights_1_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_3_ce0 = grp_load_params_func_2_fu_138_local_weights_1_0_ce0;
    end else begin
        local_weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_3_we0 = grp_load_params_func_2_fu_138_local_weights_1_0_we0;
    end else begin
        local_weights_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_4_address0 = grp_convolution_func_2_fu_194_local_weights_1_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_4_address0 = grp_load_params_func_2_fu_138_local_weights_1_1_address0;
    end else begin
        local_weights_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_4_ce0 = grp_convolution_func_2_fu_194_local_weights_1_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_4_ce0 = grp_load_params_func_2_fu_138_local_weights_1_1_ce0;
    end else begin
        local_weights_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_4_we0 = grp_load_params_func_2_fu_138_local_weights_1_1_we0;
    end else begin
        local_weights_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_5_address0 = grp_convolution_func_2_fu_194_local_weights_1_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_5_address0 = grp_load_params_func_2_fu_138_local_weights_1_2_address0;
    end else begin
        local_weights_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_5_ce0 = grp_convolution_func_2_fu_194_local_weights_1_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_5_ce0 = grp_load_params_func_2_fu_138_local_weights_1_2_ce0;
    end else begin
        local_weights_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_5_we0 = grp_load_params_func_2_fu_138_local_weights_1_2_we0;
    end else begin
        local_weights_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_6_address0 = grp_convolution_func_2_fu_194_local_weights_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_6_address0 = grp_load_params_func_2_fu_138_local_weights_2_0_address0;
    end else begin
        local_weights_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_6_ce0 = grp_convolution_func_2_fu_194_local_weights_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_6_ce0 = grp_load_params_func_2_fu_138_local_weights_2_0_ce0;
    end else begin
        local_weights_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_6_we0 = grp_load_params_func_2_fu_138_local_weights_2_0_we0;
    end else begin
        local_weights_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_7_address0 = grp_convolution_func_2_fu_194_local_weights_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_7_address0 = grp_load_params_func_2_fu_138_local_weights_2_1_address0;
    end else begin
        local_weights_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_7_ce0 = grp_convolution_func_2_fu_194_local_weights_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_7_ce0 = grp_load_params_func_2_fu_138_local_weights_2_1_ce0;
    end else begin
        local_weights_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_7_we0 = grp_load_params_func_2_fu_138_local_weights_2_1_we0;
    end else begin
        local_weights_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_8_address0 = grp_convolution_func_2_fu_194_local_weights_2_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_8_address0 = grp_load_params_func_2_fu_138_local_weights_2_2_address0;
    end else begin
        local_weights_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_8_ce0 = grp_convolution_func_2_fu_194_local_weights_2_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_8_ce0 = grp_load_params_func_2_fu_138_local_weights_2_2_ce0;
    end else begin
        local_weights_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_8_we0 = grp_load_params_func_2_fu_138_local_weights_2_2_we0;
    end else begin
        local_weights_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_address0 = grp_convolution_func_2_fu_194_local_weights_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_address0 = grp_load_params_func_2_fu_138_local_weights_0_0_address0;
    end else begin
        local_weights_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        local_weights_ce0 = grp_convolution_func_2_fu_194_local_weights_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_ce0 = grp_load_params_func_2_fu_138_local_weights_0_0_ce0;
    end else begin
        local_weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        local_weights_we0 = grp_load_params_func_2_fu_138_local_weights_0_0_we0;
    end else begin
        local_weights_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_buf_address0 = grp_write_output_func_2_fu_218_output_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_buf_address0 = grp_convolution_func_2_fu_194_output_buf_address0;
    end else begin
        output_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_buf_ce0 = grp_write_output_func_2_fu_218_output_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_buf_ce0 = grp_convolution_func_2_fu_194_output_buf_ce0;
    end else begin
        output_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        output_buf_we0 = grp_convolution_func_2_fu_194_output_buf_we0;
    end else begin
        output_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_convolution_func_2_fu_194_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_write_output_func_2_fu_218_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call26 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call27 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_prepare_input_buf_func_2_fu_170_ap_done == 1'b0) | (grp_load_params_func_2_fu_138_ap_done == 1'b0));
end

assign conv1_out_din = grp_write_output_func_2_fu_218_conv1_out_din;

assign conv1_out_write = grp_write_output_func_2_fu_218_conv1_out_write;

assign grp_convolution_func_2_fu_194_ap_start = grp_convolution_func_2_fu_194_ap_start_reg;

assign grp_load_params_func_2_fu_138_ap_start = grp_load_params_func_2_fu_138_ap_start_reg;

assign grp_prepare_input_buf_func_2_fu_170_ap_start = grp_prepare_input_buf_func_2_fu_170_ap_start_reg;

assign grp_write_output_func_2_fu_218_ap_start = grp_write_output_func_2_fu_218_ap_start_reg;

assign input_s_read = grp_prepare_input_buf_func_2_fu_170_input_s_read;

assign m_axi_gmem2_0_ARADDR = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARADDR;

assign m_axi_gmem2_0_ARBURST = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARBURST;

assign m_axi_gmem2_0_ARCACHE = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARCACHE;

assign m_axi_gmem2_0_ARID = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARID;

assign m_axi_gmem2_0_ARLEN = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARLEN;

assign m_axi_gmem2_0_ARLOCK = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARLOCK;

assign m_axi_gmem2_0_ARPROT = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARPROT;

assign m_axi_gmem2_0_ARQOS = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARQOS;

assign m_axi_gmem2_0_ARREGION = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARREGION;

assign m_axi_gmem2_0_ARSIZE = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARSIZE;

assign m_axi_gmem2_0_ARUSER = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARUSER;

assign m_axi_gmem2_0_ARVALID = grp_load_params_func_2_fu_138_m_axi_gmem2_0_ARVALID;

assign m_axi_gmem2_0_AWADDR = 32'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_RREADY = grp_load_params_func_2_fu_138_m_axi_gmem2_0_RREADY;

assign m_axi_gmem2_0_WDATA = 16'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 2'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign m_axi_gmem3_0_ARADDR = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARADDR;

assign m_axi_gmem3_0_ARBURST = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARBURST;

assign m_axi_gmem3_0_ARCACHE = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARCACHE;

assign m_axi_gmem3_0_ARID = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARID;

assign m_axi_gmem3_0_ARLEN = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARLEN;

assign m_axi_gmem3_0_ARLOCK = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARLOCK;

assign m_axi_gmem3_0_ARPROT = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARPROT;

assign m_axi_gmem3_0_ARQOS = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARQOS;

assign m_axi_gmem3_0_ARREGION = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARREGION;

assign m_axi_gmem3_0_ARSIZE = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARSIZE;

assign m_axi_gmem3_0_ARUSER = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARUSER;

assign m_axi_gmem3_0_ARVALID = grp_load_params_func_2_fu_138_m_axi_gmem3_0_ARVALID;

assign m_axi_gmem3_0_AWADDR = 32'd0;

assign m_axi_gmem3_0_AWBURST = 2'd0;

assign m_axi_gmem3_0_AWCACHE = 4'd0;

assign m_axi_gmem3_0_AWID = 1'd0;

assign m_axi_gmem3_0_AWLEN = 32'd0;

assign m_axi_gmem3_0_AWLOCK = 2'd0;

assign m_axi_gmem3_0_AWPROT = 3'd0;

assign m_axi_gmem3_0_AWQOS = 4'd0;

assign m_axi_gmem3_0_AWREGION = 4'd0;

assign m_axi_gmem3_0_AWSIZE = 3'd0;

assign m_axi_gmem3_0_AWUSER = 1'd0;

assign m_axi_gmem3_0_AWVALID = 1'b0;

assign m_axi_gmem3_0_BREADY = 1'b0;

assign m_axi_gmem3_0_RREADY = grp_load_params_func_2_fu_138_m_axi_gmem3_0_RREADY;

assign m_axi_gmem3_0_WDATA = 16'd0;

assign m_axi_gmem3_0_WID = 1'd0;

assign m_axi_gmem3_0_WLAST = 1'b0;

assign m_axi_gmem3_0_WSTRB = 2'd0;

assign m_axi_gmem3_0_WUSER = 1'd0;

assign m_axi_gmem3_0_WVALID = 1'b0;

endmodule //cnn_top_compute_4
