

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "13", "91", "111", "117", "137", "143", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156"],
		"CDFG" : "cnn_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2439577", "EstimateLatencyMax" : "2439577",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "10", "Name" : "entry_proc_U0"},
			{"ID" : "11", "Name" : "read_input_top_U0"},
			{"ID" : "13", "Name" : "compute_4_U0"},
			{"ID" : "91", "Name" : "compute_3_U0"},
			{"ID" : "117", "Name" : "compute_2_U0"}],
		"OutputProcess" : [
			{"ID" : "143", "Name" : "Block_entry_gmem1_wr_proc_U0"}],
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "read_input_top_U0", "Port" : "gmem0"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "143", "SubInstance" : "Block_entry_gmem1_wr_proc_U0", "Port" : "gmem1"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "compute_4_U0", "Port" : "gmem2"}]},
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "compute_4_U0", "Port" : "gmem3"}]},
			{"Name" : "gmem4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "91", "SubInstance" : "compute_3_U0", "Port" : "gmem4"}]},
			{"Name" : "gmem5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "91", "SubInstance" : "compute_3_U0", "Port" : "gmem5"}]},
			{"Name" : "gmem6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "117", "SubInstance" : "compute_2_U0", "Port" : "gmem6"}]},
			{"Name" : "gmem7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "117", "SubInstance" : "compute_2_U0", "Port" : "gmem7"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv1_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv1_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv2_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv2_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv3_bias", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem3_m_axi_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem4_m_axi_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem5_m_axi_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem6_m_axi_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem7_m_axi_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_r_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["143"], "DependentChan" : "147", "DependentChanDepth" : "8", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "output_r_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_input_top_U0", "Parent" : "0", "Child" : ["12"],
		"CDFG" : "read_input_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1032", "EstimateLatencyMax" : "1032",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "input_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_s", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["13"], "DependentChan" : "148", "DependentChanDepth" : "256", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "input_s_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_184_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_input_top_U0.flow_control_loop_pipe_U", "Parent" : "11"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_4_U0", "Parent" : "0", "Child" : ["14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "39", "52", "89"],
		"CDFG" : "compute_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "43627", "EstimateLatencyMax" : "43627",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_load_params_func_2_fu_138", "Port" : "gmem2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "this_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_load_params_func_2_fu_138", "Port" : "gmem3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "this_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_s", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["11"], "DependentChan" : "148", "DependentChanDepth" : "256", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "39", "SubInstance" : "grp_prepare_input_buf_func_2_fu_170", "Port" : "input_s", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "conv1_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["91"], "DependentChan" : "149", "DependentChanDepth" : "8192", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "89", "SubInstance" : "grp_write_output_func_2_fu_218", "Port" : "conv1_out", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}]},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_U", "Parent" : "13"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_1_U", "Parent" : "13"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_2_U", "Parent" : "13"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_3_U", "Parent" : "13"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_4_U", "Parent" : "13"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_5_U", "Parent" : "13"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_6_U", "Parent" : "13"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_7_U", "Parent" : "13"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.input_buf_8_U", "Parent" : "13"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.output_buf_U", "Parent" : "13"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_U", "Parent" : "13"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_1_U", "Parent" : "13"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_2_U", "Parent" : "13"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_3_U", "Parent" : "13"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_4_U", "Parent" : "13"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_5_U", "Parent" : "13"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_6_U", "Parent" : "13"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_7_U", "Parent" : "13"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_weights_8_U", "Parent" : "13"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.local_bias_U", "Parent" : "13"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_load_params_func_2_fu_138", "Parent" : "13", "Child" : ["35", "37"],
		"CDFG" : "load_params_func_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "983", "EstimateLatencyMax" : "983",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "gmem2", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "this_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem3_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_40_5_fu_115", "Port" : "gmem3", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "this_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_weights_0_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_0_0", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_0_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_0_1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_0_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_0_2", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_1_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_1_0", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_1_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_1_1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_1_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_1_2", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_2_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_2_0", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_2_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_2_1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_weights_2_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "35", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Port" : "local_weights_2_2", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_load_params_func_2_Pipeline_VITIS_LOOP_40_5_fu_115", "Port" : "local_bias", "Inst_start_state" : "19", "Inst_end_state" : "20"}]}]},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_load_params_func_2_fu_138.grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90", "Parent" : "34", "Child" : ["36"],
		"CDFG" : "load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "866", "EstimateLatencyMax" : "866",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln26", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_weights_0_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_0_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_0_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_1_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_1_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_1_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_2_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_2_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "local_weights_2_2", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "36", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_load_params_func_2_fu_138.grp_load_params_func_2_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_30_3_VITIS_LOOP_31_4_fu_90.flow_control_loop_pipe_sequential_init_U", "Parent" : "35"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_load_params_func_2_fu_138.grp_load_params_func_2_Pipeline_VITIS_LOOP_40_5_fu_115", "Parent" : "34", "Child" : ["38"],
		"CDFG" : "load_params_func_2_Pipeline_VITIS_LOOP_40_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "98", "EstimateLatencyMax" : "98",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem3_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln40", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_40_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "38", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_load_params_func_2_fu_138.grp_load_params_func_2_Pipeline_VITIS_LOOP_40_5_fu_115.flow_control_loop_pipe_sequential_init_U", "Parent" : "37"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170", "Parent" : "13", "Child" : ["40", "46"],
		"CDFG" : "prepare_input_buf_func_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1571", "EstimateLatencyMax" : "1571",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_s", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_s", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_0_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_0_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_0_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_0_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_0_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_0_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_0_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_0_2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_0_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_1_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_1_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_1_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_1_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_1_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_1_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_1_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_1_2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_1_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_2_0", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_2_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_2_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_2_1", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_2_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_2_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf_2_2", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "40", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Port" : "input_buf_2_2", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "46", "SubInstance" : "grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Port" : "input_buf_2_2", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34", "Parent" : "39", "Child" : ["41", "42", "43", "44", "45"],
		"CDFG" : "prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1303", "EstimateLatencyMax" : "1303",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf_2_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_2_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_2_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_1_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_1_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_1_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_0_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_0_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_0_0", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_51_2_VITIS_LOOP_52_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "41", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34.urem_5ns_3ns_2_9_1_U34", "Parent" : "40"},
	{"ID" : "42", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34.urem_5ns_3ns_2_9_1_U35", "Parent" : "40"},
	{"ID" : "43", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34.mul_5ns_7ns_11_1_1_U36", "Parent" : "40"},
	{"ID" : "44", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34.mul_5ns_7ns_11_1_1_U37", "Parent" : "40"},
	{"ID" : "45", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34.flow_control_loop_pipe_sequential_init_U", "Parent" : "40"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56", "Parent" : "39", "Child" : ["47", "48", "49", "50", "51"],
		"CDFG" : "prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "265", "EstimateLatencyMax" : "265",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf_2_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_2_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_2_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_1_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_1_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_1_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_0_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_0_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_buf_0_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "input_s", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "input_s_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_59_4_VITIS_LOOP_61_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "47", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56.mul_5ns_7ns_11_1_1_U49", "Parent" : "46"},
	{"ID" : "48", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56.urem_5ns_3ns_2_9_1_U50", "Parent" : "46"},
	{"ID" : "49", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56.urem_5ns_3ns_2_9_1_U51", "Parent" : "46"},
	{"ID" : "50", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56.mul_5ns_7ns_11_1_1_U52", "Parent" : "46"},
	{"ID" : "51", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_prepare_input_buf_func_2_fu_170.grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56.flow_control_loop_pipe_sequential_init_U", "Parent" : "46"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194", "Parent" : "13", "Child" : ["53", "85", "86", "87", "88"],
		"CDFG" : "convolution_func_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "17473", "EstimateLatencyMax" : "17473",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf_0_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_0_0", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_0_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_0_1", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_0_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_0_2", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_1_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_1_0", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_1_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_1_1", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_1_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_1_2", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_2_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_2_0", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_2_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_2_1", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "input_buf_2_2", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "input_buf_2_2", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "local_weights_0_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_0_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_0_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_1_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_1_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_1_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_2_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_2_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights_2_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Port" : "output_buf", "Inst_start_state" : "11", "Inst_end_state" : "12"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_79_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "12", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state12"], "QuitState" : ["ap_ST_fsm_state12"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_77_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "12", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state12"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254", "Parent" : "52", "Child" : ["54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84"],
		"CDFG" : "convolution_func_2_Pipeline_VITIS_LOOP_81_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "25", "EstimateLatencyMax" : "25",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "mul_ln90_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_buf_0_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "mul_ln90_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "mul_ln90_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "input_buf_0_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_0_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_1_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_1_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_1_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_2_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_2_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "input_buf_2_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "empty_41", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_17", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln90_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "sum", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "i", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_81_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "54", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U73", "Parent" : "53"},
	{"ID" : "55", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U74", "Parent" : "53"},
	{"ID" : "56", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U75", "Parent" : "53"},
	{"ID" : "57", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U76", "Parent" : "53"},
	{"ID" : "58", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U77", "Parent" : "53"},
	{"ID" : "59", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U78", "Parent" : "53"},
	{"ID" : "60", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U79", "Parent" : "53"},
	{"ID" : "61", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U80", "Parent" : "53"},
	{"ID" : "62", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U81", "Parent" : "53"},
	{"ID" : "63", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mul_4ns_6ns_9_1_1_U82", "Parent" : "53"},
	{"ID" : "64", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mul_5ns_7ns_11_1_1_U83", "Parent" : "53"},
	{"ID" : "65", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mul_5ns_7ns_11_1_1_U84", "Parent" : "53"},
	{"ID" : "66", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U85", "Parent" : "53"},
	{"ID" : "67", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U86", "Parent" : "53"},
	{"ID" : "68", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U87", "Parent" : "53"},
	{"ID" : "69", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U88", "Parent" : "53"},
	{"ID" : "70", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U89", "Parent" : "53"},
	{"ID" : "71", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U90", "Parent" : "53"},
	{"ID" : "72", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U91", "Parent" : "53"},
	{"ID" : "73", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U92", "Parent" : "53"},
	{"ID" : "74", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.sparsemux_7_2_16_1_1_U93", "Parent" : "53"},
	{"ID" : "75", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mul_16s_16s_28_1_1_U94", "Parent" : "53"},
	{"ID" : "76", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mul_16s_16s_28_1_1_U95", "Parent" : "53"},
	{"ID" : "77", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mul_16s_16s_28_1_1_U96", "Parent" : "53"},
	{"ID" : "78", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mac_muladd_16s_16s_28s_28_4_1_U97", "Parent" : "53"},
	{"ID" : "79", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mac_muladd_16s_16s_28s_28_4_1_U98", "Parent" : "53"},
	{"ID" : "80", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mac_muladd_16s_16s_28s_28_4_1_U99", "Parent" : "53"},
	{"ID" : "81", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mac_muladd_16s_16s_28ns_28_4_1_U100", "Parent" : "53"},
	{"ID" : "82", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mac_muladd_16s_16s_28ns_28_4_1_U101", "Parent" : "53"},
	{"ID" : "83", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.mac_muladd_16s_16s_28ns_28_4_1_U102", "Parent" : "53"},
	{"ID" : "84", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.grp_convolution_func_2_Pipeline_VITIS_LOOP_81_3_fu_254.flow_control_loop_pipe_sequential_init_U", "Parent" : "53"},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.urem_4ns_3ns_2_8_seq_1_U136", "Parent" : "52"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.mul_4ns_6ns_9_1_1_U137", "Parent" : "52"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.mul_5ns_7ns_11_1_1_U138", "Parent" : "52"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_convolution_func_2_fu_194.am_addmul_4ns_2ns_6ns_11_4_1_U139", "Parent" : "52"},
	{"ID" : "89", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_write_output_func_2_fu_218", "Parent" : "13", "Child" : ["90"],
		"CDFG" : "write_output_func_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "24578", "EstimateLatencyMax" : "24578",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv1_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "conv1_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_103_1_VITIS_LOOP_105_2_VITIS_LOOP_106_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "90", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_4_U0.grp_write_output_func_2_fu_218.flow_control_loop_pipe_sequential_init_U", "Parent" : "89"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_3_U0", "Parent" : "0", "Child" : ["92", "93", "94", "95", "96", "101", "106", "109"],
		"CDFG" : "compute_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2439574", "EstimateLatencyMax" : "2439574",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem4", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "96", "SubInstance" : "grp_load_params_func_1_fu_74", "Port" : "gmem4", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "this_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem5", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "96", "SubInstance" : "grp_load_params_func_1_fu_74", "Port" : "gmem5", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "this_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "conv1_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["13"], "DependentChan" : "149", "DependentChanDepth" : "8192", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "101", "SubInstance" : "grp_prepare_input_buf_func_1_fu_90", "Port" : "conv1_out", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "conv2_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["111"], "DependentChan" : "150", "DependentChanDepth" : "8192", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "109", "SubInstance" : "grp_write_output_func_1_fu_106", "Port" : "conv2_out", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}]},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.input_buf_U", "Parent" : "91"},
	{"ID" : "93", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.output_buf_U", "Parent" : "91"},
	{"ID" : "94", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.local_weights_U", "Parent" : "91"},
	{"ID" : "95", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.local_bias_U", "Parent" : "91"},
	{"ID" : "96", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_load_params_func_1_fu_74", "Parent" : "91", "Child" : ["97", "99"],
		"CDFG" : "load_params_func_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27767", "EstimateLatencyMax" : "27767",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem4", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem4_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "97", "SubInstance" : "grp_load_params_func_1_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITI_fu_74", "Port" : "gmem4", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "this_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem5", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem5_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "99", "SubInstance" : "grp_load_params_func_1_Pipeline_VITIS_LOOP_40_5_fu_83", "Port" : "gmem5", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "this_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_weights", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "97", "SubInstance" : "grp_load_params_func_1_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITI_fu_74", "Port" : "local_weights", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "99", "SubInstance" : "grp_load_params_func_1_Pipeline_VITIS_LOOP_40_5_fu_83", "Port" : "local_bias", "Inst_start_state" : "19", "Inst_end_state" : "20"}]}]},
	{"ID" : "97", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_load_params_func_1_fu_74.grp_load_params_func_1_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITI_fu_74", "Parent" : "96", "Child" : ["98"],
		"CDFG" : "load_params_func_1_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITI",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27650", "EstimateLatencyMax" : "27650",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem4", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem4_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln26", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_weights", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_LOOP_31_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "98", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_load_params_func_1_fu_74.grp_load_params_func_1_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITI_fu_74.flow_control_loop_pipe_sequential_init_U", "Parent" : "97"},
	{"ID" : "99", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_load_params_func_1_fu_74.grp_load_params_func_1_Pipeline_VITIS_LOOP_40_5_fu_83", "Parent" : "96", "Child" : ["100"],
		"CDFG" : "load_params_func_1_Pipeline_VITIS_LOOP_40_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "98", "EstimateLatencyMax" : "98",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem5", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem5_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln40", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_40_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "100", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_load_params_func_1_fu_74.grp_load_params_func_1_Pipeline_VITIS_LOOP_40_5_fu_83.flow_control_loop_pipe_sequential_init_U", "Parent" : "99"},
	{"ID" : "101", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_prepare_input_buf_func_1_fu_90", "Parent" : "91", "Child" : ["102", "104"],
		"CDFG" : "prepare_input_buf_func_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "55687", "EstimateLatencyMax" : "55687",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv1_out", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "104", "SubInstance" : "grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_s_fu_24", "Port" : "conv1_out", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "102", "SubInstance" : "grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_s_fu_18", "Port" : "input_buf", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "104", "SubInstance" : "grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_s_fu_24", "Port" : "input_buf", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "102", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_prepare_input_buf_func_1_fu_90.grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_s_fu_18", "Parent" : "101", "Child" : ["103"],
		"CDFG" : "prepare_input_buf_func_1_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "31106", "EstimateLatencyMax" : "31106",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "103", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_prepare_input_buf_func_1_fu_90.grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_s_fu_18.flow_control_loop_pipe_sequential_init_U", "Parent" : "102"},
	{"ID" : "104", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_prepare_input_buf_func_1_fu_90.grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_s_fu_24", "Parent" : "101", "Child" : ["105"],
		"CDFG" : "prepare_input_buf_func_1_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "24578", "EstimateLatencyMax" : "24578",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv1_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "conv1_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "105", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_prepare_input_buf_func_1_fu_90.grp_prepare_input_buf_func_1_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_s_fu_24.flow_control_loop_pipe_sequential_init_U", "Parent" : "104"},
	{"ID" : "106", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_convolution_func_1_fu_98", "Parent" : "91", "Child" : ["107", "108"],
		"CDFG" : "convolution_func_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2359304", "EstimateLatencyMax" : "2359304",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_77_1_VITIS_LOOP_79_2_VITIS_LOOP_81_3_VITIS_LOOP_84_4_VITIS_LOOP_86_5_VITIS_LOOP_87_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_convolution_func_1_fu_98.mac_muladd_16s_16s_32ns_32_4_1_U190", "Parent" : "106"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_convolution_func_1_fu_98.flow_control_loop_pipe_sequential_init_U", "Parent" : "106"},
	{"ID" : "109", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_write_output_func_1_fu_106", "Parent" : "91", "Child" : ["110"],
		"CDFG" : "write_output_func_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "24578", "EstimateLatencyMax" : "24578",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv2_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "conv2_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_103_1_VITIS_LOOP_105_2_VITIS_LOOP_106_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "110", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_3_U0.grp_write_output_func_1_fu_106.flow_control_loop_pipe_sequential_init_U", "Parent" : "109"},
	{"ID" : "111", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_1_U0", "Parent" : "0", "Child" : ["112", "113", "115"],
		"CDFG" : "compute_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "24583", "EstimateLatencyMax" : "24583",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "91",
		"StartFifo" : "start_for_compute_1_U0_U",
		"Port" : [
			{"Name" : "conv2_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["91"], "DependentChan" : "150", "DependentChanDepth" : "8192", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "113", "SubInstance" : "grp_read_input_func_1_fu_24", "Port" : "conv2_out", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "pool1_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["117"], "DependentChan" : "151", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_pooling_func_1_fu_32", "Port" : "pool1_out", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "112", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_1_U0.input_buf_U", "Parent" : "111"},
	{"ID" : "113", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_1_U0.grp_read_input_func_1_fu_24", "Parent" : "111", "Child" : ["114"],
		"CDFG" : "read_input_func_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16386", "EstimateLatencyMax" : "16386",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv2_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "conv2_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_1_VITIS_LOOP_145_2_VITIS_LOOP_146_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "114", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_1_U0.grp_read_input_func_1_fu_24.flow_control_loop_pipe_sequential_init_U", "Parent" : "113"},
	{"ID" : "115", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_1_U0.grp_pooling_func_1_fu_32", "Parent" : "111", "Child" : ["116"],
		"CDFG" : "pooling_func_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "8194", "EstimateLatencyMax" : "8194",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "pool1_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "pool1_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_155_1_VITIS_LOOP_157_2_VITIS_LOOP_158_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "116", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_1_U0.grp_pooling_func_1_fu_32.flow_control_loop_pipe_sequential_init_U", "Parent" : "115"},
	{"ID" : "117", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_2_U0", "Parent" : "0", "Child" : ["118", "119", "120", "121", "122", "127", "132", "135"],
		"CDFG" : "compute_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "623750", "EstimateLatencyMax" : "623750",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem6", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "122", "SubInstance" : "grp_load_params_func_fu_74", "Port" : "gmem6", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "this_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem7", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "122", "SubInstance" : "grp_load_params_func_fu_74", "Port" : "gmem7", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "this_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "pool1_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["111"], "DependentChan" : "151", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "127", "SubInstance" : "grp_prepare_input_buf_func_fu_90", "Port" : "pool1_out", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "conv3_out", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["137"], "DependentChan" : "152", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "135", "SubInstance" : "grp_write_output_func_fu_106", "Port" : "conv3_out", "Inst_start_state" : "5", "Inst_end_state" : "6"}]}]},
	{"ID" : "118", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.input_buf_U", "Parent" : "117"},
	{"ID" : "119", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.output_buf_U", "Parent" : "117"},
	{"ID" : "120", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.local_weights_U", "Parent" : "117"},
	{"ID" : "121", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.local_bias_U", "Parent" : "117"},
	{"ID" : "122", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_load_params_func_fu_74", "Parent" : "117", "Child" : ["123", "125"],
		"CDFG" : "load_params_func",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27767", "EstimateLatencyMax" : "27767",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem6", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem6_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "123", "SubInstance" : "grp_load_params_func_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_s_fu_74", "Port" : "gmem6", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "this_weights", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem7", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem7_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "125", "SubInstance" : "grp_load_params_func_Pipeline_VITIS_LOOP_40_5_fu_83", "Port" : "gmem7", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "this_bias", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_weights", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "123", "SubInstance" : "grp_load_params_func_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_s_fu_74", "Port" : "local_weights", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "125", "SubInstance" : "grp_load_params_func_Pipeline_VITIS_LOOP_40_5_fu_83", "Port" : "local_bias", "Inst_start_state" : "19", "Inst_end_state" : "20"}]}]},
	{"ID" : "123", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_load_params_func_fu_74.grp_load_params_func_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_s_fu_74", "Parent" : "122", "Child" : ["124"],
		"CDFG" : "load_params_func_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "27650", "EstimateLatencyMax" : "27650",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem6", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem6_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln26", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_weights", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_LOOP_31_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "124", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_load_params_func_fu_74.grp_load_params_func_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_28_2_VITIS_LOOP_30_3_VITIS_s_fu_74.flow_control_loop_pipe_sequential_init_U", "Parent" : "123"},
	{"ID" : "125", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_load_params_func_fu_74.grp_load_params_func_Pipeline_VITIS_LOOP_40_5_fu_83", "Parent" : "122", "Child" : ["126"],
		"CDFG" : "load_params_func_Pipeline_VITIS_LOOP_40_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "98", "EstimateLatencyMax" : "98",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem7", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem7_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln40", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_40_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "126", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_load_params_func_fu_74.grp_load_params_func_Pipeline_VITIS_LOOP_40_5_fu_83.flow_control_loop_pipe_sequential_init_U", "Parent" : "125"},
	{"ID" : "127", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_prepare_input_buf_func_fu_90", "Parent" : "117", "Child" : ["128", "130"],
		"CDFG" : "prepare_input_buf_func",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15751", "EstimateLatencyMax" : "15751",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "pool1_out", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "130", "SubInstance" : "grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6_fu_24", "Port" : "pool1_out", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "128", "SubInstance" : "grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_18", "Port" : "input_buf", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "130", "SubInstance" : "grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6_fu_24", "Port" : "input_buf", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "128", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_prepare_input_buf_func_fu_90.grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_18", "Parent" : "127", "Child" : ["129"],
		"CDFG" : "prepare_input_buf_func_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "9602", "EstimateLatencyMax" : "9602",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "129", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_prepare_input_buf_func_fu_90.grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_49_1_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_18.flow_control_loop_pipe_sequential_init_U", "Parent" : "128"},
	{"ID" : "130", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_prepare_input_buf_func_fu_90.grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6_fu_24", "Parent" : "127", "Child" : ["131"],
		"CDFG" : "prepare_input_buf_func_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6146", "EstimateLatencyMax" : "6146",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "pool1_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "pool1_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "131", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_prepare_input_buf_func_fu_90.grp_prepare_input_buf_func_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_VITIS_LOOP_62_6_fu_24.flow_control_loop_pipe_sequential_init_U", "Parent" : "130"},
	{"ID" : "132", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_convolution_func_fu_98", "Parent" : "117", "Child" : ["133", "134"],
		"CDFG" : "convolution_func",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "589832", "EstimateLatencyMax" : "589832",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_weights", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_bias", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_77_1_VITIS_LOOP_79_2_VITIS_LOOP_81_3_VITIS_LOOP_84_4_VITIS_LOOP_86_5_VITIS_LOOP_87_6", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "133", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_convolution_func_fu_98.mac_muladd_16s_16s_32ns_32_4_1_U232", "Parent" : "132"},
	{"ID" : "134", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_convolution_func_fu_98.flow_control_loop_pipe_sequential_init_U", "Parent" : "132"},
	{"ID" : "135", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_write_output_func_fu_106", "Parent" : "117", "Child" : ["136"],
		"CDFG" : "write_output_func",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6146", "EstimateLatencyMax" : "6146",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv3_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "conv3_out_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_103_1_VITIS_LOOP_105_2_VITIS_LOOP_106_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "136", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_2_U0.grp_write_output_func_fu_106.flow_control_loop_pipe_sequential_init_U", "Parent" : "135"},
	{"ID" : "137", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0", "Parent" : "0", "Child" : ["138", "139", "141"],
		"CDFG" : "compute",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "6151", "EstimateLatencyMax" : "6151",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "117",
		"StartFifo" : "start_for_compute_U0_U",
		"Port" : [
			{"Name" : "conv3_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["117"], "DependentChan" : "152", "DependentChanDepth" : "2048", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "139", "SubInstance" : "grp_read_input_func_fu_24", "Port" : "conv3_out", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "output_s", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["143"], "DependentChan" : "153", "DependentChanDepth" : "512", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "141", "SubInstance" : "grp_pooling_func_fu_32", "Port" : "output_s", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}]},
	{"ID" : "138", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.input_buf_U", "Parent" : "137"},
	{"ID" : "139", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_read_input_func_fu_24", "Parent" : "137", "Child" : ["140"],
		"CDFG" : "read_input_func",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4098", "EstimateLatencyMax" : "4098",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "conv3_out", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "conv3_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_143_1_VITIS_LOOP_145_2_VITIS_LOOP_146_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state2", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state2_blk", "QuitState" : "ap_ST_fsm_state2", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state2_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "140", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_read_input_func_fu_24.flow_control_loop_pipe_sequential_init_U", "Parent" : "139"},
	{"ID" : "141", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_pooling_func_fu_32", "Parent" : "137", "Child" : ["142"],
		"CDFG" : "pooling_func",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2050", "EstimateLatencyMax" : "2050",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "output_s", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "output_s_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_155_1_VITIS_LOOP_157_2_VITIS_LOOP_158_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "142", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_pooling_func_fu_32.flow_control_loop_pipe_sequential_init_U", "Parent" : "141"},
	{"ID" : "143", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem1_wr_proc_U0", "Parent" : "0", "Child" : ["144"],
		"CDFG" : "Block_entry_gmem1_wr_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1554", "EstimateLatencyMax" : "1554",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "10",
		"StartFifo" : "start_for_Block_entry_gmem1_wr_proc_U0_U",
		"Port" : [
			{"Name" : "output_r", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["10"], "DependentChan" : "147", "DependentChanDepth" : "8", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "output_r_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "144", "SubInstance" : "grp_write_output_top_fu_83", "Port" : "gmem1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "output_s", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["137"], "DependentChan" : "153", "DependentChanDepth" : "512", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "144", "SubInstance" : "grp_write_output_top_fu_83", "Port" : "output_s", "Inst_start_state" : "9", "Inst_end_state" : "10"}]}]},
	{"ID" : "144", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem1_wr_proc_U0.grp_write_output_top_fu_83", "Parent" : "143", "Child" : ["145"],
		"CDFG" : "write_output_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1545", "EstimateLatencyMax" : "1545",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "output_s", "Type" : "Fifo", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "145", "SubInstance" : "grp_write_output_top_Pipeline_VITIS_LOOP_192_1_fu_60", "Port" : "output_s", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_B", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "145", "SubInstance" : "grp_write_output_top_Pipeline_VITIS_LOOP_192_1_fu_60", "Port" : "gmem1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "output_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "145", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem1_wr_proc_U0.grp_write_output_top_fu_83.grp_write_output_top_Pipeline_VITIS_LOOP_192_1_fu_60", "Parent" : "144", "Child" : ["146"],
		"CDFG" : "write_output_top_Pipeline_VITIS_LOOP_192_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1538", "EstimateLatencyMax" : "1538",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln192", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_s", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "output_s_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_192_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "3", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state3", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state3_blk", "QuitState" : "ap_ST_fsm_state3", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state3_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "146", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem1_wr_proc_U0.grp_write_output_top_fu_83.grp_write_output_top_Pipeline_VITIS_LOOP_192_1_fu_60.flow_control_loop_pipe_sequential_init_U", "Parent" : "145"},
	{"ID" : "147", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.output_r_c_U", "Parent" : "0"},
	{"ID" : "148", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.input_s_U", "Parent" : "0"},
	{"ID" : "149", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv1_out_U", "Parent" : "0"},
	{"ID" : "150", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv2_out_U", "Parent" : "0"},
	{"ID" : "151", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pool1_out_U", "Parent" : "0"},
	{"ID" : "152", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv3_out_U", "Parent" : "0"},
	{"ID" : "153", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.output_s_U", "Parent" : "0"},
	{"ID" : "154", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_Block_entry_gmem1_wr_proc_U0_U", "Parent" : "0"},
	{"ID" : "155", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_1_U0_U", "Parent" : "0"},
	{"ID" : "156", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_U0_U", "Parent" : "0"}]}
