-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_top_prepare_input_buf_func_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    input_s_empty_n : IN STD_LOGIC;
    input_s_read : OUT STD_LOGIC;
    input_s_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
    input_s_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
    input_buf_0_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_0_0_ce0 : OUT STD_LOGIC;
    input_buf_0_0_we0 : OUT STD_LOGIC;
    input_buf_0_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_0_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_0_1_ce0 : OUT STD_LOGIC;
    input_buf_0_1_we0 : OUT STD_LOGIC;
    input_buf_0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_0_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_0_2_ce0 : OUT STD_LOGIC;
    input_buf_0_2_we0 : OUT STD_LOGIC;
    input_buf_0_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_1_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_1_0_ce0 : OUT STD_LOGIC;
    input_buf_1_0_we0 : OUT STD_LOGIC;
    input_buf_1_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_1_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_1_1_ce0 : OUT STD_LOGIC;
    input_buf_1_1_we0 : OUT STD_LOGIC;
    input_buf_1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_1_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_1_2_ce0 : OUT STD_LOGIC;
    input_buf_1_2_we0 : OUT STD_LOGIC;
    input_buf_1_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_2_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_2_0_ce0 : OUT STD_LOGIC;
    input_buf_2_0_we0 : OUT STD_LOGIC;
    input_buf_2_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_2_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_2_1_ce0 : OUT STD_LOGIC;
    input_buf_2_1_we0 : OUT STD_LOGIC;
    input_buf_2_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_buf_2_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_buf_2_2_ce0 : OUT STD_LOGIC;
    input_buf_2_2_we0 : OUT STD_LOGIC;
    input_buf_2_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of cnn_top_prepare_input_buf_func_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_idle : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_ready : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_idle : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_ready : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_s_read : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0 : STD_LOGIC;
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_top_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_buf_2_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_2_2_ce0 : OUT STD_LOGIC;
        input_buf_2_2_we0 : OUT STD_LOGIC;
        input_buf_2_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_2_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_2_1_ce0 : OUT STD_LOGIC;
        input_buf_2_1_we0 : OUT STD_LOGIC;
        input_buf_2_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_2_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_2_0_ce0 : OUT STD_LOGIC;
        input_buf_2_0_we0 : OUT STD_LOGIC;
        input_buf_2_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_1_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_1_2_ce0 : OUT STD_LOGIC;
        input_buf_1_2_we0 : OUT STD_LOGIC;
        input_buf_1_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_1_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_1_1_ce0 : OUT STD_LOGIC;
        input_buf_1_1_we0 : OUT STD_LOGIC;
        input_buf_1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_1_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_1_0_ce0 : OUT STD_LOGIC;
        input_buf_1_0_we0 : OUT STD_LOGIC;
        input_buf_1_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_0_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_0_2_ce0 : OUT STD_LOGIC;
        input_buf_0_2_we0 : OUT STD_LOGIC;
        input_buf_0_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_0_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_0_1_ce0 : OUT STD_LOGIC;
        input_buf_0_1_we0 : OUT STD_LOGIC;
        input_buf_0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_0_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_0_0_ce0 : OUT STD_LOGIC;
        input_buf_0_0_we0 : OUT STD_LOGIC;
        input_buf_0_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component cnn_top_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        input_s_empty_n : IN STD_LOGIC;
        input_s_read : OUT STD_LOGIC;
        input_s_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        input_s_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        input_buf_2_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_2_2_ce0 : OUT STD_LOGIC;
        input_buf_2_2_we0 : OUT STD_LOGIC;
        input_buf_2_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_2_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_2_1_ce0 : OUT STD_LOGIC;
        input_buf_2_1_we0 : OUT STD_LOGIC;
        input_buf_2_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_2_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_2_0_ce0 : OUT STD_LOGIC;
        input_buf_2_0_we0 : OUT STD_LOGIC;
        input_buf_2_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_1_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_1_2_ce0 : OUT STD_LOGIC;
        input_buf_1_2_we0 : OUT STD_LOGIC;
        input_buf_1_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_1_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_1_1_ce0 : OUT STD_LOGIC;
        input_buf_1_1_we0 : OUT STD_LOGIC;
        input_buf_1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_1_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_1_0_ce0 : OUT STD_LOGIC;
        input_buf_1_0_we0 : OUT STD_LOGIC;
        input_buf_1_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_0_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_0_2_ce0 : OUT STD_LOGIC;
        input_buf_0_2_we0 : OUT STD_LOGIC;
        input_buf_0_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_0_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_0_1_ce0 : OUT STD_LOGIC;
        input_buf_0_1_we0 : OUT STD_LOGIC;
        input_buf_0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_buf_0_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_buf_0_0_ce0 : OUT STD_LOGIC;
        input_buf_0_0_we0 : OUT STD_LOGIC;
        input_buf_0_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34 : component cnn_top_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start,
        ap_done => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done,
        ap_idle => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_idle,
        ap_ready => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_ready,
        input_buf_2_2_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0,
        input_buf_2_2_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0,
        input_buf_2_2_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0,
        input_buf_2_2_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0,
        input_buf_2_1_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0,
        input_buf_2_1_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0,
        input_buf_2_1_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0,
        input_buf_2_1_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0,
        input_buf_2_0_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0,
        input_buf_2_0_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0,
        input_buf_2_0_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0,
        input_buf_2_0_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0,
        input_buf_1_2_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0,
        input_buf_1_2_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0,
        input_buf_1_2_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0,
        input_buf_1_2_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0,
        input_buf_1_1_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0,
        input_buf_1_1_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0,
        input_buf_1_1_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0,
        input_buf_1_1_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0,
        input_buf_1_0_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0,
        input_buf_1_0_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0,
        input_buf_1_0_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0,
        input_buf_1_0_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0,
        input_buf_0_2_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0,
        input_buf_0_2_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0,
        input_buf_0_2_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0,
        input_buf_0_2_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0,
        input_buf_0_1_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0,
        input_buf_0_1_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0,
        input_buf_0_1_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0,
        input_buf_0_1_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0,
        input_buf_0_0_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0,
        input_buf_0_0_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0,
        input_buf_0_0_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0,
        input_buf_0_0_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0);

    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56 : component cnn_top_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start,
        ap_done => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done,
        ap_idle => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_idle,
        ap_ready => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_ready,
        input_s_dout => input_s_dout,
        input_s_empty_n => input_s_empty_n,
        input_s_read => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_s_read,
        input_s_num_data_valid => ap_const_lv9_0,
        input_s_fifo_cap => ap_const_lv9_0,
        input_buf_2_2_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0,
        input_buf_2_2_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0,
        input_buf_2_2_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0,
        input_buf_2_2_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0,
        input_buf_2_1_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0,
        input_buf_2_1_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0,
        input_buf_2_1_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0,
        input_buf_2_1_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0,
        input_buf_2_0_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0,
        input_buf_2_0_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0,
        input_buf_2_0_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0,
        input_buf_2_0_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0,
        input_buf_1_2_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0,
        input_buf_1_2_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0,
        input_buf_1_2_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0,
        input_buf_1_2_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0,
        input_buf_1_1_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0,
        input_buf_1_1_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0,
        input_buf_1_1_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0,
        input_buf_1_1_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0,
        input_buf_1_0_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0,
        input_buf_1_0_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0,
        input_buf_1_0_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0,
        input_buf_1_0_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0,
        input_buf_0_2_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0,
        input_buf_0_2_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0,
        input_buf_0_2_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0,
        input_buf_0_2_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0,
        input_buf_0_1_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0,
        input_buf_0_1_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0,
        input_buf_0_1_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0,
        input_buf_0_1_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0,
        input_buf_0_0_address0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0,
        input_buf_0_0_ce0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0,
        input_buf_0_0_we0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0,
        input_buf_0_0_d0 => grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_ready = ap_const_logic_1)) then 
                    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done)
    begin
        if ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done)
    begin
        if ((grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done = ap_const_logic_1)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_ap_start_reg;
    grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_ap_start_reg;

    input_buf_0_0_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_0_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_0_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_address0;
        else 
            input_buf_0_0_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_0_0_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_0_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_0_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_ce0;
        else 
            input_buf_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_0_0_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_0_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_0_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_d0;
        else 
            input_buf_0_0_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_0_0_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_0_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_0_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_0_we0;
        else 
            input_buf_0_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_0_1_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_1_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_1_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_address0;
        else 
            input_buf_0_1_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_0_1_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_1_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_1_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_ce0;
        else 
            input_buf_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_0_1_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_1_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_1_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_d0;
        else 
            input_buf_0_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_0_1_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_1_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_1_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_1_we0;
        else 
            input_buf_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_0_2_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_2_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_2_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_address0;
        else 
            input_buf_0_2_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_0_2_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_2_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_2_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_ce0;
        else 
            input_buf_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_0_2_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_2_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_2_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_d0;
        else 
            input_buf_0_2_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_0_2_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_0_2_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_0_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_0_2_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_0_2_we0;
        else 
            input_buf_0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_1_0_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_0_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_0_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_address0;
        else 
            input_buf_1_0_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_1_0_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_0_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_0_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_ce0;
        else 
            input_buf_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_1_0_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_0_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_0_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_d0;
        else 
            input_buf_1_0_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_1_0_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_0_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_0_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_0_we0;
        else 
            input_buf_1_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_1_1_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_1_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_1_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_address0;
        else 
            input_buf_1_1_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_1_1_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_1_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_1_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_ce0;
        else 
            input_buf_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_1_1_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_1_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_1_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_d0;
        else 
            input_buf_1_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_1_1_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_1_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_1_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_1_we0;
        else 
            input_buf_1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_1_2_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_2_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_2_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_address0;
        else 
            input_buf_1_2_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_1_2_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_2_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_2_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_ce0;
        else 
            input_buf_1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_1_2_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_2_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_2_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_d0;
        else 
            input_buf_1_2_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_1_2_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_1_2_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_1_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_1_2_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_1_2_we0;
        else 
            input_buf_1_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_2_0_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_0_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_0_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_address0;
        else 
            input_buf_2_0_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_2_0_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_0_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_0_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_ce0;
        else 
            input_buf_2_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_2_0_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_0_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_0_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_d0;
        else 
            input_buf_2_0_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_2_0_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_0_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_0_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_0_we0;
        else 
            input_buf_2_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_2_1_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_1_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_1_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_address0;
        else 
            input_buf_2_1_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_2_1_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_1_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_1_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_ce0;
        else 
            input_buf_2_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_2_1_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_1_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_1_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_d0;
        else 
            input_buf_2_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_2_1_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_1_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_1_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_1_we0;
        else 
            input_buf_2_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_2_2_address0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_2_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_2_address0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_address0;
        else 
            input_buf_2_2_address0 <= "XXXXXX";
        end if; 
    end process;


    input_buf_2_2_ce0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_2_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_2_ce0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_ce0;
        else 
            input_buf_2_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_buf_2_2_d0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_2_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_2_d0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_d0;
        else 
            input_buf_2_2_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    input_buf_2_2_we0_assign_proc : process(grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0, grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_buf_2_2_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_buf_2_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_buf_2_2_we0 <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_51_2_VITIS_LOOP_52_3_fu_34_input_buf_2_2_we0;
        else 
            input_buf_2_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    input_s_read <= grp_prepare_input_buf_func_2_Pipeline_VITIS_LOOP_59_4_VITIS_LOOP_61_5_fu_56_input_s_read;
end behav;
